using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EasyPlayscript;

[Generator]
public class PlayscriptRunner : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("ScriptBlock.g.cs", SourceText.From(GenerateScriptBlock(), Encoding.UTF8));
            ctx.AddSource("PlayscriptRunner.g.cs", SourceText.From(GeneratePlayscriptRunner(), Encoding.UTF8));
        });
    }

    private static string GenerateScriptBlock()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class ScriptBlock");
        indented.WriteLine("{");
        indented.Indent++;
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string GeneratePlayscriptRunner()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class PlayscriptRunner");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public void Script(string name, ScriptBlock scriptBlock)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("// TODO: Implement playscript execution");
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }
}
