using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using EasyPlayscript.Parsing;

namespace EasyPlayscript;

public static class PlayscriptBaseEmitter
{
    public static string Generate(
        Dictionary<string, ScriptBlock> scripts,
        Dictionary<string, TextBlock> texts,
        List<InterfaceDeclaration> interfaces,
        string outputPath,
        string aesKey,
        string className)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine($"public abstract class {className}");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine(
            "private readonly System.Lazy<System.Collections.Generic.Dictionary<string, ScriptBlock>> _scripts;");
        indented.WriteLine(
            "private readonly System.Lazy<System.Collections.Generic.Dictionary<string, TextBlock>> _texts;");
        indented.WriteLine();

        indented.WriteLine($"protected {className}(string outputPath, string aesKey)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("_scripts = new System.Lazy<System.Collections.Generic.Dictionary<string, ScriptBlock>>(");
        indented.Indent++;
        indented.WriteLine("() => PlayscriptLoader.LoadScripts(outputPath, aesKey));");
        indented.Indent--;
        indented.WriteLine("_texts = new System.Lazy<System.Collections.Generic.Dictionary<string, TextBlock>>(");
        indented.Indent++;
        indented.WriteLine("() => PlayscriptLoader.LoadTexts(outputPath, aesKey));");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        var sortedScripts = scripts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal);
        foreach (var kvp in sortedScripts)
        {
            var propName = ToScreamingSnakeCase(kvp.Key);
            indented.WriteLine(
                $"public Script {propName} => new Script {{ Block = _scripts.Value[\"{kvp.Key}\"], Dispatch = DispatchCall }};");
        }

        var sortedTexts = texts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal);
        foreach (var kvp in sortedTexts)
        {
            var propName = ToScreamingSnakeCase(kvp.Key);
            indented.WriteLine(
                $"public Text {propName} => new Text {{ Block = _texts.Value[\"{kvp.Key}\"], Dispatch = DispatchCall }};");
        }

        if (scripts.Count > 0 || texts.Count > 0)
            indented.WriteLine();

        var sortedInterfaces = interfaces.OrderBy(i => i.Name, StringComparer.Ordinal);
        foreach (var iface in sortedInterfaces)
        {
            var returnTypeName = MapReturnType(iface.ReturnType);
            var paramList = string.Join(", ",
                iface.Parameters.Select(p => $"{MapParameterType(p.Type)} {p.Name}"));
            indented.WriteLine($"public abstract {returnTypeName} {iface.Name}({paramList});");
        }

        if (interfaces.Count > 0)
            indented.WriteLine();

        indented.WriteLine("internal void DispatchCall(ConsumerCallItem call)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (call.Identifier)");
        indented.WriteLine("{");
        indented.Indent++;

        foreach (var iface in sortedInterfaces)
        {
            indented.Indent++;
            indented.WriteLine($"case \"{iface.Name}\":");
            indented.Indent++;

            var argList = string.Join(", ",
                iface.Parameters.Select((p, i) => $"(({MapArgumentType(p.Type)})call.Arguments[{i}]).Value"));

            if (iface.ReturnType == InterfaceType.Void)
            {
                indented.WriteLine($"{iface.Name}({argList});");
            }
            else
            {
                indented.WriteLine($"call.Result = {iface.Name}({argList});");
            }

            indented.WriteLine("break;");
            indented.Indent--;
            indented.Indent--;
        }

        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string MapReturnType(InterfaceType type)
    {
        switch (type)
        {
            case InterfaceType.String: return "string";
            case InterfaceType.Int: return "int";
            case InterfaceType.Decimal: return "double";
            case InterfaceType.Bool: return "bool";
            case InterfaceType.Void: return "void";
            default: return "object";
        }
    }

    private static string MapParameterType(InterfaceType type)
    {
        return MapReturnType(type);
    }

    private static string MapArgumentType(InterfaceType type)
    {
        return type switch
        {
            InterfaceType.String => "StringArgument",
            InterfaceType.Int => "IntArgument",
            InterfaceType.Decimal => "DoubleArgument",
            InterfaceType.Bool => "BoolArgument",
            _ => "ArgumentValue"
        };
    }

    private static string ToScreamingSnakeCase(string name)
    {
        var sb = new StringBuilder();
        foreach (var c in name)
        {
            sb.Append(c is ' ' or '-' ? '_' : char.ToUpperInvariant(c));
        }

        return sb.ToString();
    }
}
