using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EasyPlayscript.Parsing;

namespace EasyPlayscript;

public static class PlayscriptBaseEmitter
{
    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
        "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    ];

    public static string Generate(
        Dictionary<string, ScriptBlock> scripts,
        Dictionary<string, TextBlock> texts,
        List<InterfaceDeclaration> interfaces,
        string outputPath,
        string aesKey,
        string className)
    {
        var normalizedPath = outputPath.Replace('\\', '/');
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine($"public abstract class {className}");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine(
            "private readonly System.Lazy<System.Collections.Generic.Dictionary<string, ScriptBlock>> _scripts;");
        indented.WriteLine(
            "private readonly System.Lazy<System.Collections.Generic.Dictionary<string, TextBlock>> _texts;");
        indented.WriteLine();

        indented.WriteLine($"protected {className}()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("_scripts = new System.Lazy<System.Collections.Generic.Dictionary<string, ScriptBlock>>(");
        indented.Indent++;
        indented.WriteLine($"() => PlayscriptLoader.LoadScripts(\"{normalizedPath}\", \"{aesKey}\"));");
        indented.Indent--;
        indented.WriteLine("_texts = new System.Lazy<System.Collections.Generic.Dictionary<string, TextBlock>>(");
        indented.Indent++;
        indented.WriteLine($"() => PlayscriptLoader.LoadTexts(\"{normalizedPath}\", \"{aesKey}\"));");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        var sortedScripts = scripts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal).ToList();
        if (sortedScripts.Count > 0)
        {
            indented.WriteLine("public enum ScriptKey");
            indented.WriteLine("{");
            indented.Indent++;
            for (var i = 0; i < sortedScripts.Count; i++)
            {
                var suffix = i < sortedScripts.Count - 1 ? "," : "";
                indented.WriteLine($"{EscapeKeyword(sortedScripts[i].Key)}{suffix}");
            }

            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
            indented.WriteLine("public Script GetScript(ScriptKey key) => new Script { Block = _scripts.Value[ScriptKeyToString(key)], Dispatch = DispatchCall };");
            indented.WriteLine();
            indented.WriteLine("private static string ScriptKeyToString(ScriptKey key) => key switch");
            indented.WriteLine("{");
            indented.Indent++;
            foreach (var kvp in sortedScripts)
                indented.WriteLine($"ScriptKey.{EscapeKeyword(kvp.Key)} => \"{kvp.Key}\",");
            indented.WriteLine("_ => throw new System.ArgumentOutOfRangeException(nameof(key), key, null)");
            indented.Indent--;
            indented.WriteLine("};");
        }

        var sortedTexts = texts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal).ToList();
        if (sortedTexts.Count > 0)
        {
            indented.WriteLine("public enum TextKey");
            indented.WriteLine("{");
            indented.Indent++;
            for (var i = 0; i < sortedTexts.Count; i++)
            {
                var suffix = i < sortedTexts.Count - 1 ? "," : "";
                indented.WriteLine($"{EscapeKeyword(sortedTexts[i].Key)}{suffix}");
            }

            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
            indented.WriteLine("public Text GetText(TextKey key) => new Text { Block = _texts.Value[TextKeyToString(key)], Dispatch = DispatchCall };");
            indented.WriteLine();
            indented.WriteLine("private static string TextKeyToString(TextKey key) => key switch");
            indented.WriteLine("{");
            indented.Indent++;
            foreach (var kvp in sortedTexts)
                indented.WriteLine($"TextKey.{EscapeKeyword(kvp.Key)} => \"{kvp.Key}\",");
            indented.WriteLine("_ => throw new System.ArgumentOutOfRangeException(nameof(key), key, null)");
            indented.Indent--;
            indented.WriteLine("};");
        }

        if (scripts.Count > 0 || texts.Count > 0)
            indented.WriteLine();

        var sortedInterfaces = interfaces
            .OrderBy(i => i.Name, StringComparer.Ordinal).ToList();
        foreach (var iface in sortedInterfaces)
        {
            var returnTypeName = MapReturnType(iface.ReturnType);
            var paramList = string.Join(", ",
                iface.Parameters.Select(p => $"{MapParameterType(p.Type)} {p.Name}"));
            indented.WriteLine($"public abstract {returnTypeName} {iface.Name}({paramList});");
        }

        if (interfaces.Count > 0)
            indented.WriteLine();

        indented.WriteLine("internal void DispatchCall(ConsumerCallItem call)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (call.Identifier)");
        indented.WriteLine("{");
        indented.Indent++;

        foreach (var iface in sortedInterfaces)
        {
            indented.Indent++;
            indented.WriteLine($"case \"{iface.Name}\":");
            indented.Indent++;

            var argList = string.Join(", ",
                iface.Parameters.Select((p, i) => $"(({MapArgumentType(p.Type)})call.Arguments[{i}]).Value"));

            if (iface.ReturnType == InterfaceType.Void)
            {
                indented.WriteLine($"{iface.Name}({argList});");
            }
            else
                indented.WriteLine($"call.Result = {iface.Name}({argList});");

            indented.WriteLine("break;");
            indented.Indent--;
            indented.Indent--;
        }

        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string EscapeKeyword(string name) => CSharpKeywords.Contains(name) ? $"@{name}" : name;

    private static string MapReturnType(InterfaceType type)
    {
        return type switch
        {
            InterfaceType.String => "string",
            InterfaceType.Int => "int",
            InterfaceType.Decimal => "double",
            InterfaceType.Bool => "bool",
            InterfaceType.Void => "void",
            _ => "object"
        };
    }

    private static string MapParameterType(InterfaceType type)
    {
        return MapReturnType(type);
    }

    private static string MapArgumentType(InterfaceType type)
    {
        return type switch
        {
            InterfaceType.String => "StringArgument",
            InterfaceType.Int => "IntArgument",
            InterfaceType.Decimal => "DoubleArgument",
            InterfaceType.Bool => "BoolArgument",
            _ => "ArgumentValue"
        };
    }
}