using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EasyPlayscript;

[Generator]
public class ScriptRegistry : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("Script.g.cs", SourceText.From(GenerateScript(), Encoding.UTF8));
            ctx.AddSource("Text.g.cs", SourceText.From(GenerateText(), Encoding.UTF8));
            ctx.AddSource("ScriptRegistry.g.cs", SourceText.From(GenerateScriptRegistry(), Encoding.UTF8));
        });
    }

    private static string GenerateScript()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("using System.Collections.Generic;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class Script");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public List<ScriptBlock> Blocks { get; } = new List<ScriptBlock>();");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string GenerateText()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("using System.Collections.Generic;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class Text");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public List<ScriptBlock> Blocks { get; } = new List<ScriptBlock>();");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string GenerateScriptRegistry()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("using System.Collections.Generic;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class ScriptRegistry");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public Dictionary<string, Script> Scripts { get; } = new Dictionary<string, Script>();");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }
}
