using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EasyPlayscript;

/// <summary>
/// Source generator that emits data classes (<c>Script</c>, <c>Text</c>)
/// via <see cref="IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput"/> into the
/// <c>EasyPlayscript.Generated</c> namespace.
/// </summary>
[Generator]
public class ScriptRegistry : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("Script.g.cs", SourceText.From(GenerateScript(), Encoding.UTF8));
            ctx.AddSource("Text.g.cs", SourceText.From(GenerateText(), Encoding.UTF8));
        });
    }

    private static string GenerateScript()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class Script");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public ScriptBlock Block { get; set; }");
        indented.WriteLine("internal Action<ConsumerCallItem>? Dispatch { get; set; }");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string GenerateText()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class Text");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public TextBlock Block { get; set; }");
        indented.WriteLine("internal Action<ConsumerCallItem>? Dispatch { get; set; }");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }
}
