using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EasyPlayscript.Parsing;

namespace EasyPlayscript.Generator;

public static class PlayscriptRegistryEmitter
{
    public static string Generate(PlayscriptCompilationData data)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.DataModel;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public sealed class PlayscriptRegistry");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine("internal void DispatchCall(ConsumerCallItem call, PlayscriptRuntimeSession session)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (call.Identifier)");
        indented.WriteLine("{");
        indented.Indent++;

        var interfacesByName = data.Interfaces
            .GroupBy(i => i.Name)
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var group in interfacesByName)
        {
            var overloads = group.OrderBy(i => i.Parameters.Count).ToList();
            var hasMultipleOverloads = overloads.Count > 1;

            foreach (var iface in overloads)
            {
                var impl = FindMatchingImplementation(data.Implementations, iface);
                if (impl == null) continue;

                indented.Indent++;
                indented.WriteLine(hasMultipleOverloads
                    ? $"case \"{iface.Name}\" when call.Arguments.Count == {iface.Parameters.Count}:"
                    : $"case \"{iface.Name}\":");
                indented.WriteLine("{");
                indented.Indent++;

                var argList = string.Join(", ",
                    iface.Parameters.Select((p, i) =>
                        $"(({MapArgumentType(p.Type)})call.Arguments[{i}]).Value"));

                var shortName = impl.ClassName.Split(["::", "."], StringSplitOptions.RemoveEmptyEntries).Last();
                var localName = $"_{CamelCase(impl.ClassName)}";

                indented.WriteLine($"var {localName} = session.Get<{impl.ClassName}>();");
                indented.WriteLine(
                    $"if ({localName} == null) throw new NullReferenceException(\"EasyPlayscript: {shortName} was not registered before script execution.\");");
                indented.WriteLine(iface.ReturnType == InterfaceType.Void
                    ? $"{localName}.{impl.MethodName}({argList});"
                    : $"call.Result = {localName}.{impl.MethodName}({argList});");

                indented.WriteLine("break;");
                indented.Indent--;
                indented.WriteLine("}");
                indented.Indent--;
            }
        }

        indented.WriteLine("default:");
        indented.Indent++;
        indented.WriteLine("throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("$\"EasyPlayscript: Unhandled action '{call.Identifier}'.\");");
        indented.Indent--;
        indented.Indent--;

        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static ImplementationInfo? FindMatchingImplementation(
        List<ImplementationInfo> implementations, InterfaceDeclaration iface)
    {
        return implementations.FirstOrDefault(i =>
            i.EffectiveName == iface.Name &&
            i.ParameterTypeNames.Count == iface.Parameters.Count);
    }

    private static string CamelCase(string qualifiedName)
    {
        var parts = qualifiedName.Split(["::", "."], StringSplitOptions.RemoveEmptyEntries);
        var name = parts.Last();
        if (name.Length == 0) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string MapArgumentType(InterfaceType type)
    {
        return type switch
        {
            InterfaceType.String => "StringArgument",
            InterfaceType.Int => "IntArgument",
            InterfaceType.Decimal => "DoubleArgument",
            InterfaceType.Bool => "BoolArgument",
            _ => "ArgumentValue"
        };
    }
}