using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EasyPlayscript.DataModel;

namespace EasyPlayscript.Generator;

public static class PlayscriptRuntimeEmitter
{
    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
        "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    ];

    public static string Generate(
        Dictionary<string, ScriptVariants> scripts,
        Dictionary<string, TextVariants> texts,
        string outputPath,
        bool hasAsync = false)
    {
        var normalizedPath = outputPath.Replace('\\', '/');
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using System.Collections.Generic;");
        indented.WriteLine("using System.IO;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.DataModel;");
        indented.WriteLine("using EasyPlayscript.Runtime;");
        indented.WriteLine("using System.Threading.Tasks;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();

        // ── Top-level enums (namespace scope, for Godot export compatibility) ──

        // Per-script variation enums
        EmitVariationEnums(scripts, "Script", indented);
        EmitVariationEnums(texts, "Text", indented);

        // ScriptKey enum + ToString switch
        var sortedScripts = scripts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal).ToList();
        if (sortedScripts.Count > 0)
        {
            indented.WriteLine("public enum ScriptKey");
            indented.WriteLine("{");
            indented.Indent++;
            for (var i = 0; i < sortedScripts.Count; i++)
            {
                var suffix = i < sortedScripts.Count - 1 ? "," : "";
                indented.WriteLine($"{EscapeKeyword(sortedScripts[i].Key)}{suffix}");
            }
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();

            indented.WriteLine("internal static class ScriptKeyHelper");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("public static string ToString(ScriptKey key) => key switch");
            indented.WriteLine("{");
            indented.Indent++;
            foreach (var kvp in sortedScripts)
                indented.WriteLine($"ScriptKey.{EscapeKeyword(kvp.Key)} => \"{kvp.Key}\",");
            indented.WriteLine("_ => throw new ArgumentOutOfRangeException(nameof(key), key, null)");
            indented.Indent--;
            indented.WriteLine("};");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
        }

        // TextKey enum + ToString switch
        var sortedTexts = texts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal).ToList();
        if (sortedTexts.Count > 0)
        {
            if (sortedScripts.Count > 0) indented.WriteLine();
            indented.WriteLine("public enum TextKey");
            indented.WriteLine("{");
            indented.Indent++;
            for (var i = 0; i < sortedTexts.Count; i++)
            {
                var suffix = i < sortedTexts.Count - 1 ? "," : "";
                indented.WriteLine($"{EscapeKeyword(sortedTexts[i].Key)}{suffix}");
            }
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();

            indented.WriteLine("internal static class TextKeyHelper");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("public static string ToString(TextKey key) => key switch");
            indented.WriteLine("{");
            indented.Indent++;
            foreach (var kvp in sortedTexts)
                indented.WriteLine($"TextKey.{EscapeKeyword(kvp.Key)} => \"{kvp.Key}\",");
            indented.WriteLine("_ => throw new ArgumentOutOfRangeException(nameof(key), key, null)");
            indented.Indent--;
            indented.WriteLine("};");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
        }

        // ── Class ──
        indented.WriteLine("public class PlayscriptRuntimeSession : PlayscriptSessionScope");
        indented.WriteLine("{");
        indented.Indent++;

        // ── Fields & properties ──
        indented.WriteLine("private readonly string? _aesKey;");
        indented.WriteLine("private readonly Lazy<Dictionary<string, ScriptVariants>> _scripts;");
        indented.WriteLine("private readonly Lazy<Dictionary<string, TextVariants>> _texts;");
        indented.WriteLine("public PlayscriptRegistry Registry { get; }");
        indented.WriteLine();

        // ── Public constructors ──
        indented.WriteLine("public PlayscriptRuntimeSession() : this((string?)null) { }");
        indented.WriteLine();
        indented.WriteLine("public PlayscriptRuntimeSession(string? aesKey) : this(new PlayscriptRegistry(), aesKey) { }");
        indented.WriteLine();
        indented.WriteLine("public PlayscriptRuntimeSession(PlayscriptRegistry registry, string? aesKey) : base()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("Registry = registry ?? throw new ArgumentNullException(nameof(registry));");
        indented.WriteLine("_aesKey = aesKey;");
        indented.WriteLine("_scripts = new Lazy<Dictionary<string, ScriptVariants>>(");
        indented.Indent++;
        indented.WriteLine($"() => PlayscriptLoader.LoadScripts(ResolvePath(\"{normalizedPath}\"), _aesKey));");
        indented.Indent--;
        indented.WriteLine("_texts = new Lazy<Dictionary<string, TextVariants>>(");
        indented.Indent++;
        indented.WriteLine($"() => PlayscriptLoader.LoadTexts(ResolvePath(\"{normalizedPath}\"), _aesKey));");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        // ── Private child constructor ──
        indented.WriteLine("private PlayscriptRuntimeSession(PlayscriptRegistry registry, string? aesKey, PlayscriptSessionScope parent) : base(parent)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("Registry = registry;");
        indented.WriteLine("_aesKey = aesKey;");
        indented.WriteLine("_scripts = new Lazy<Dictionary<string, ScriptVariants>>(");
        indented.Indent++;
        indented.WriteLine($"() => PlayscriptLoader.LoadScripts(ResolvePath(\"{normalizedPath}\"), _aesKey));");
        indented.Indent--;
        indented.WriteLine("_texts = new Lazy<Dictionary<string, TextVariants>>(");
        indented.Indent++;
        indented.WriteLine($"() => PlayscriptLoader.LoadTexts(ResolvePath(\"{normalizedPath}\"), _aesKey));");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        // ── CreateChild ──
        indented.WriteLine("public override PlayscriptRuntimeSession CreateChild()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("return new PlayscriptRuntimeSession(Registry, _aesKey, this);");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        // ── Dispatch ──
        indented.WriteLine("public void DispatchCall(ConsumerCallItem call)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("Registry.DispatchCall(call, this);");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        indented.WriteLine("public async Task DispatchCallAsync(ConsumerCallItem call)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("await Registry.DispatchCallAsync(call, this);");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        // ── GetScript overloads ──
        if (sortedScripts.Count > 0)
        {
            indented.WriteLine("public Script GetScript(string name)");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("if (!_scripts.Value.TryGetValue(name, out var variants))");
            indented.Indent++;
            indented.WriteLine("throw new InvalidOperationException($\"Script '{name}' not found.\");");
            indented.Indent--;
            indented.WriteLine("if (variants.Unversioned == null)");
            indented.Indent++;
            indented.WriteLine("throw new InvalidOperationException($\"Script '{name}' has no unversioned block.\");");
            indented.Indent--;
            indented.WriteLine("return new Script");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("Block = variants.Unversioned,");
            indented.WriteLine("Runtime = this");
            indented.Indent--;
            indented.WriteLine("};");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();

            indented.WriteLine("public Script GetScript(string name, string variation)");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("if (!_scripts.Value.TryGetValue(name, out var variants))");
            indented.Indent++;
            indented.WriteLine("throw new InvalidOperationException($\"Script '{name}' not found.\");");
            indented.Indent--;
            indented.WriteLine("if (!variants.Numbered.TryGetValue(variation, out var block))");
            indented.Indent++;
            indented.WriteLine("throw new InvalidOperationException($\"Script '{name}' has no variation '{variation}'.\");");
            indented.Indent--;
            indented.WriteLine("return new Script");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("Block = block,");
            indented.WriteLine("Runtime = this");
            indented.Indent--;
            indented.WriteLine("};");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();

            indented.WriteLine("public Script GetScript(ScriptKey key) => GetScript(ScriptKeyHelper.ToString(key));");
            indented.WriteLine();
            indented.WriteLine("public Script GetScript(ScriptKey key, string variation) => GetScript(ScriptKeyHelper.ToString(key), variation);");
            indented.WriteLine();

            indented.WriteLine("public Script GetScript<TVar>(ScriptKey key, TVar variation)");
            indented.WriteLine("    where TVar : struct, Enum");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("return GetScript(key, variation.ToString().ToLowerInvariant());");
            indented.Indent--;
            indented.WriteLine("}");
        }

        // ── GetText overloads ──
        if (sortedTexts.Count > 0)
        {
            if (sortedScripts.Count > 0) indented.WriteLine();

            indented.WriteLine("public Text GetText(string name)");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("if (!_texts.Value.TryGetValue(name, out var variants))");
            indented.Indent++;
            indented.WriteLine("throw new InvalidOperationException($\"Text '{name}' not found.\");");
            indented.Indent--;
            indented.WriteLine("if (variants.Unversioned == null)");
            indented.Indent++;
            indented.WriteLine("throw new InvalidOperationException($\"Text '{name}' has no unversioned block.\");");
            indented.Indent--;
            indented.WriteLine("return new Text");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("Block = variants.Unversioned,");
            indented.WriteLine("Runtime = this");
            indented.Indent--;
            indented.WriteLine("};");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();

            indented.WriteLine("public Text GetText(string name, string variation)");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("if (!_texts.Value.TryGetValue(name, out var variants))");
            indented.Indent++;
            indented.WriteLine("throw new InvalidOperationException($\"Text '{name}' not found.\");");
            indented.Indent--;
            indented.WriteLine("if (!variants.Numbered.TryGetValue(variation, out var block))");
            indented.Indent++;
            indented.WriteLine("throw new InvalidOperationException($\"Text '{name}' has no variation '{variation}'.\");");
            indented.Indent--;
            indented.WriteLine("return new Text");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("Block = block,");
            indented.WriteLine("Runtime = this");
            indented.Indent--;
            indented.WriteLine("};");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();

            indented.WriteLine("public Text GetText(TextKey key) => GetText(TextKeyHelper.ToString(key));");
            indented.WriteLine();
            indented.WriteLine("public Text GetText(TextKey key, string variation) => GetText(TextKeyHelper.ToString(key), variation);");
            indented.WriteLine();

            indented.WriteLine("public Text GetText<TVar>(TextKey key, TVar variation)");
            indented.WriteLine("    where TVar : struct, Enum");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("return GetText(key, variation.ToString().ToLowerInvariant());");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
        }

        // ── ResolvePath ──
        indented.WriteLine("private static string ResolvePath(string path) =>");
        indented.Indent++;
        indented.WriteLine(
            "Path.IsPathRooted(path) ? path : Path.Combine(AppDomain.CurrentDomain.BaseDirectory, path);");
        indented.Indent--;

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static void EmitVariationEnums(Dictionary<string, ScriptVariants> scripts, string prefix, IndentedTextWriter indented)
    {
        foreach (var kvp in scripts)
        {
            if (kvp.Value.Numbered.Count == 0) continue;

            var enumName = $"{EscapeKeyword(kvp.Key)}{prefix}Variation";
            indented.WriteLine($"public enum {enumName}");
            indented.WriteLine("{");
            indented.Indent++;
            var keys = kvp.Value.Numbered.Keys.OrderBy(k => k, StringComparer.Ordinal).ToList();
            for (var i = 0; i < keys.Count; i++)
            {
                var suffix = i < keys.Count - 1 ? "," : "";
                var memberName = ToPascalCase(keys[i]);
                indented.WriteLine($"{EscapeKeyword(memberName)}{suffix}");
            }
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
        }
    }

    private static void EmitVariationEnums(Dictionary<string, TextVariants> texts, string prefix, IndentedTextWriter indented)
    {
        foreach (var kvp in texts)
        {
            if (kvp.Value.Numbered.Count == 0) continue;

            var enumName = $"{EscapeKeyword(kvp.Key)}{prefix}Variation";
            indented.WriteLine($"public enum {enumName}");
            indented.WriteLine("{");
            indented.Indent++;
            var keys = kvp.Value.Numbered.Keys.OrderBy(k => k, StringComparer.Ordinal).ToList();
            for (var i = 0; i < keys.Count; i++)
            {
                var suffix = i < keys.Count - 1 ? "," : "";
                var memberName = ToPascalCase(keys[i]);
                indented.WriteLine($"{EscapeKeyword(memberName)}{suffix}");
            }
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
        }
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name)) return name;
        return char.ToUpperInvariant(name[0]) + name.Substring(1);
    }

    private static string EscapeKeyword(string name)
    {
        return CSharpKeywords.Contains(name) ? $"@{name}" : name;
    }
}
