using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EasyPlayscript.Parsing;

namespace EasyPlayscript.Generator;

public static class PlayscriptRegistryEmitter
{
    public static string Generate(PlayscriptCompilationData data)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public sealed class PlayscriptRegistry");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine("private readonly System.Collections.Generic.Dictionary<System.Type, object> _globals = new();");
        indented.WriteLine();
        indented.WriteLine("public void RegisterGlobal<T>(T instance) where T : class");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("_globals[typeof(T)] = instance ?? throw new ArgumentNullException(nameof(instance));");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        indented.WriteLine("internal void DispatchCall(ConsumerCallItem call, TransientNodeContext context)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (call.Identifier)");
        indented.WriteLine("{");
        indented.Indent++;

        var interfacesByName = data.Interfaces
            .GroupBy(i => i.Name)
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var group in interfacesByName)
        {
            var overloads = group.OrderBy(i => i.Parameters.Count).ToList();
            var hasMultipleOverloads = overloads.Count > 1;

            foreach (var iface in overloads)
            {
                var impl = FindMatchingImplementation(data.Implementations, iface);
                if (impl == null) continue;

                indented.Indent++;
                if (hasMultipleOverloads)
                    indented.WriteLine($"case \"{iface.Name}\" when call.Arguments.Count == {iface.Parameters.Count}:");
                else
                    indented.WriteLine($"case \"{iface.Name}\":");
                indented.WriteLine("{");
                indented.Indent++;

                var argList = string.Join(", ",
                    iface.Parameters.Select((p, i) =>
                        $"(({MapArgumentType(p.Type)})call.Arguments[{i}]).Value"));

                var shortName = impl.ClassName.Split(["::", "."], StringSplitOptions.RemoveEmptyEntries).Last();

                if (impl.Scope == ActionScope.TransientNode)
                {
                    var localName = $"_{CamelCase(impl.ClassName)}Node";
                    indented.WriteLine($"var {localName} = context.Get<{impl.ClassName}>();");
                    indented.WriteLine(
                        $"if ({localName} == null) throw new NullReferenceException(\"EasyPlayscript: {shortName} missing from execution context.\");");
                    if (iface.ReturnType == InterfaceType.Void)
                        indented.WriteLine($"{localName}.{impl.MethodName}({argList});");
                    else
                        indented.WriteLine($"call.Result = {localName}.{impl.MethodName}({argList});");
                }
                else
                {
                    var localName = $"_{CamelCase(impl.ClassName)}";
                    indented.WriteLine(
                        $"if (!_globals.TryGetValue(typeof({impl.ClassName}), out var {localName}Obj)) throw new NullReferenceException(\"EasyPlayscript: {shortName} instance was not registered before script execution.\");");
                    indented.WriteLine($"var {localName} = ({impl.ClassName}){localName}Obj;");
                    indented.WriteLine(iface.ReturnType == InterfaceType.Void
                        ? $"{localName}.{impl.MethodName}({argList});"
                        : $"call.Result = {localName}.{impl.MethodName}({argList});");
                }

                indented.WriteLine("break;");
                indented.Indent--;
                indented.WriteLine("}");
                indented.Indent--;
            }
        }

        indented.WriteLine("default:");
        indented.Indent++;
        indented.WriteLine("throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("$\"EasyPlayscript: Unhandled action '{call.Identifier}'.\");");
        indented.Indent--;
        indented.Indent--;

        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static ImplementationInfo? FindMatchingImplementation(
        List<ImplementationInfo> implementations, InterfaceDeclaration iface)
    {
        return implementations.FirstOrDefault(i =>
            i.EffectiveName == iface.Name &&
            i.ParameterTypeNames.Count == iface.Parameters.Count);
    }

    private static string CamelCase(string qualifiedName)
    {
        var parts = qualifiedName.Split(new[] { "::", "." }, StringSplitOptions.RemoveEmptyEntries);
        var name = parts.Last();
        if (name.Length == 0) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string MapArgumentType(InterfaceType type)
    {
        return type switch
        {
            InterfaceType.String => "StringArgument",
            InterfaceType.Int => "IntArgument",
            InterfaceType.Decimal => "DoubleArgument",
            InterfaceType.Bool => "BoolArgument",
            _ => "ArgumentValue"
        };
    }
}