using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EasyPlayscript.Parsing;

namespace EasyPlayscript.Generator;

public static class PlayscriptSessionEmitter
{
    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
        "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    ];

    public static string Generate(
        List<ImplementationInfo> implementations,
        Dictionary<string, ScriptBlock> scripts,
        Dictionary<string, TextBlock> texts)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class PlayscriptSession : PlayscriptContext");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine("public TransientNodeContext SceneContext { get; } = new();");
        indented.WriteLine();

        indented.WriteLine("public PlayscriptSession() : base(new PlayscriptRegistry()) { }");
        indented.WriteLine();

        indented.WriteLine("public void Register<T>(T instance, ActionScope scope) where T : class");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (scope)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("case ActionScope.GlobalService:");
        indented.Indent++;
        indented.WriteLine("Registry.RegisterGlobal(instance);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.WriteLine("case ActionScope.TransientNode:");
        indented.Indent++;
        indented.WriteLine("SceneContext.Bind(instance);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.WriteLine("default:");
        indented.Indent++;
        indented.WriteLine("throw new ArgumentOutOfRangeException(nameof(scope));");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        indented.WriteLine("public void DispatchCall(ConsumerCallItem call)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("Registry.DispatchCall(call, SceneContext);");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        var sortedScripts = scripts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal).ToList();
        if (sortedScripts.Count > 0)
        {
            indented.WriteLine("public new Script GetScript(ScriptKey key)");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("var script = ((PlayscriptContext)this).GetScript(key);");
            indented.WriteLine("script.Session = this;");
            indented.WriteLine("return script;");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
        }

        var sortedTexts = texts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal).ToList();
        if (sortedTexts.Count > 0)
        {
            indented.WriteLine("public new Text GetText(TextKey key)");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("var text = ((PlayscriptContext)this).GetText(key);");
            indented.WriteLine("text.Session = this;");
            indented.WriteLine("return text;");
            indented.Indent--;
            indented.WriteLine("}");
        }

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }
}
