using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace EasyPlayscript.Generator;

public static class PlayscriptContextEmitter
{
    private static readonly HashSet<string> CSharpKeywords =
    [
        "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
        "checked", "class", "const", "continue", "decimal", "default", "delegate",
        "do", "double", "else", "enum", "event", "explicit", "extern", "false",
        "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
        "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
        "new", "null", "object", "operator", "out", "override", "params", "private",
        "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
        "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
        "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
        "unsafe", "ushort", "using", "virtual", "void", "volatile", "while"
    ];

    public static string Generate(
        Dictionary<string, ScriptBlock> scripts,
        Dictionary<string, TextBlock> texts,
        string outputPath,
        string aesKey)
    {
        var normalizedPath = outputPath.Replace('\\', '/');
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using System.Collections.Generic;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public sealed class PlayscriptContext");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine(
            "private readonly System.Lazy<System.Collections.Generic.Dictionary<string, ScriptBlock>> _scripts;");
        indented.WriteLine(
            "private readonly System.Lazy<System.Collections.Generic.Dictionary<string, TextBlock>> _texts;");
        indented.WriteLine("private readonly PlayscriptRegistry _registry;");
        indented.WriteLine();

        indented.WriteLine("public PlayscriptContext(PlayscriptRegistry registry)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("_registry = registry ?? throw new ArgumentNullException(nameof(registry));");
        indented.WriteLine("_scripts = new System.Lazy<System.Collections.Generic.Dictionary<string, ScriptBlock>>(");
        indented.Indent++;
        indented.WriteLine($"() => PlayscriptLoader.LoadScripts(ResolvePath(\"{normalizedPath}\"), \"{aesKey}\"));");
        indented.Indent--;
        indented.WriteLine("_texts = new System.Lazy<System.Collections.Generic.Dictionary<string, TextBlock>>(");
        indented.Indent++;
        indented.WriteLine($"() => PlayscriptLoader.LoadTexts(ResolvePath(\"{normalizedPath}\"), \"{aesKey}\"));");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        var sortedScripts = scripts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal).ToList();
        if (sortedScripts.Count > 0)
        {
            indented.WriteLine("public enum ScriptKey");
            indented.WriteLine("{");
            indented.Indent++;
            for (var i = 0; i < sortedScripts.Count; i++)
            {
                var suffix = i < sortedScripts.Count - 1 ? "," : "";
                indented.WriteLine($"{EscapeKeyword(sortedScripts[i].Key)}{suffix}");
            }

            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
            indented.WriteLine("public Script GetScript(ScriptKey key) => new Script");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("Block = _scripts.Value[ScriptKeyToString(key)]");
            indented.Indent--;
            indented.WriteLine("};");
            indented.WriteLine();
            indented.WriteLine("private static string ScriptKeyToString(ScriptKey key) => key switch");
            indented.WriteLine("{");
            indented.Indent++;
            foreach (var kvp in sortedScripts)
                indented.WriteLine($"ScriptKey.{EscapeKeyword(kvp.Key)} => \"{kvp.Key}\",");
            indented.WriteLine("_ => throw new System.ArgumentOutOfRangeException(nameof(key), key, null)");
            indented.Indent--;
            indented.WriteLine("};");
        }

        var sortedTexts = texts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal).ToList();
        if (sortedTexts.Count > 0)
        {
            indented.WriteLine("public enum TextKey");
            indented.WriteLine("{");
            indented.Indent++;
            for (var i = 0; i < sortedTexts.Count; i++)
            {
                var suffix = i < sortedTexts.Count - 1 ? "," : "";
                indented.WriteLine($"{EscapeKeyword(sortedTexts[i].Key)}{suffix}");
            }

            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
            indented.WriteLine("public Text GetText(TextKey key) => new Text");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("Block = _texts.Value[TextKeyToString(key)]");
            indented.Indent--;
            indented.WriteLine("};");
            indented.WriteLine();
            indented.WriteLine("private static string TextKeyToString(TextKey key) => key switch");
            indented.WriteLine("{");
            indented.Indent++;
            foreach (var kvp in sortedTexts)
                indented.WriteLine($"TextKey.{EscapeKeyword(kvp.Key)} => \"{kvp.Key}\",");
            indented.WriteLine("_ => throw new System.ArgumentOutOfRangeException(nameof(key), key, null)");
            indented.Indent--;
            indented.WriteLine("};");
        }

        indented.WriteLine();
        indented.WriteLine("private static string ResolvePath(string path) =>");
        indented.Indent++;
        indented.WriteLine(
            "System.IO.Path.IsPathRooted(path) ? path : System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, path);");
        indented.Indent--;

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string EscapeKeyword(string name)
    {
        return CSharpKeywords.Contains(name) ? $"@{name}" : name;
    }
}