using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using EasyPlayscript.Parsing;

namespace EasyPlayscript.Generator;

public static class PlayscriptSessionEmitter
{
    public static string Generate(
        Dictionary<string, ScriptBlock> scripts,
        Dictionary<string, TextBlock> texts)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class PlayscriptSession : PlayscriptContext");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine("public TransientNodeContext SceneContext { get; } = new();");
        indented.WriteLine();

        indented.WriteLine("public PlayscriptSession() : base(new PlayscriptRegistry()) { }");
        indented.WriteLine();

        indented.WriteLine("public void Register<T>(T instance, ActionScope scope) where T : class");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (scope)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("case ActionScope.GlobalService:");
        indented.Indent++;
        indented.WriteLine("Registry.RegisterGlobal(instance);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.WriteLine("case ActionScope.TransientNode:");
        indented.Indent++;
        indented.WriteLine("SceneContext.Bind(instance);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.WriteLine("default:");
        indented.Indent++;
        indented.WriteLine("throw new ArgumentOutOfRangeException(nameof(scope));");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        indented.WriteLine("public void DispatchCall(ConsumerCallItem call)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("Registry.DispatchCall(call, SceneContext);");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        if (scripts.Count > 0)
        {
            indented.WriteLine("public new Script GetScript(ScriptKey key)");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("var script = ((PlayscriptContext)this).GetScript(key);");
            indented.WriteLine("script.Session = this;");
            indented.WriteLine("return script;");
            indented.Indent--;
            indented.WriteLine("}");
            indented.WriteLine();
        }

        if (texts.Count > 0)
        {
            indented.WriteLine("public new Text GetText(TextKey key)");
            indented.WriteLine("{");
            indented.Indent++;
            indented.WriteLine("var text = ((PlayscriptContext)this).GetText(key);");
            indented.WriteLine("text.Session = this;");
            indented.WriteLine("return text;");
            indented.Indent--;
            indented.WriteLine("}");
        }

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }
}
