using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using EasyPlayscript.Parsing;

namespace EasyPlayscript.Generator;

public static class PlayscriptRegistryEmitter
{
    public static string Generate(PlayscriptCompilationData data)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        var hasAsync = data.Interfaces.Any(i => i.IsAsync);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.DataModel;");
        if (hasAsync)
            indented.WriteLine("using System.Threading.Tasks;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public sealed class PlayscriptRegistry");
        indented.WriteLine("{");
        indented.Indent++;

        GenerateDispatchCall(data, indented);

        if (hasAsync)
        {
            indented.WriteLine();
            GenerateDispatchCallAsync(data, indented);
        }

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static void GenerateDispatchCall(PlayscriptCompilationData data, IndentedTextWriter indented)
    {
        indented.WriteLine("internal void DispatchCall(ConsumerCallItem call, PlayscriptRuntimeSession session)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (call.Identifier)");
        indented.WriteLine("{");
        indented.Indent++;

        var interfacesByName = data.Interfaces
            .GroupBy(i => i.Name)
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var group in interfacesByName)
        {
            var overloads = group.OrderBy(i => i.Parameters.Count).ToList();
            var hasMultipleOverloads = overloads.Count > 1;

            foreach (var iface in overloads)
            {
                var impl = FindMatchingImplementation(data.Implementations, iface);
                if (impl == null) continue;

                EmitCaseHeader(indented, iface, hasMultipleOverloads);
                indented.WriteLine("{");
                indented.Indent++;

                EmitServiceResolution(indented, impl);
                EmitSyncDispatchBody(indented, iface, impl);

                indented.WriteLine("break;");
                indented.Indent--;
                indented.WriteLine("}");
                indented.Indent--;
            }
        }

        EmitDefaultCase(indented);

        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
    }

    private static void GenerateDispatchCallAsync(PlayscriptCompilationData data, IndentedTextWriter indented)
    {
        indented.WriteLine("internal async Task DispatchCallAsync(ConsumerCallItem call, PlayscriptRuntimeSession session)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (call.Identifier)");
        indented.WriteLine("{");
        indented.Indent++;

        var interfacesByName = data.Interfaces
            .GroupBy(i => i.Name)
            .OrderBy(g => g.Key, StringComparer.Ordinal);

        foreach (var group in interfacesByName)
        {
            var overloads = group.OrderBy(i => i.Parameters.Count).ToList();
            var hasMultipleOverloads = overloads.Count > 1;

            foreach (var iface in overloads)
            {
                var impl = FindMatchingImplementation(data.Implementations, iface);
                if (impl == null) continue;

                EmitCaseHeader(indented, iface, hasMultipleOverloads);
                indented.WriteLine("{");
                indented.Indent++;

                EmitServiceResolution(indented, impl);
                EmitAsyncDispatchBody(indented, iface, impl);

                indented.WriteLine("break;");
                indented.Indent--;
                indented.WriteLine("}");
                indented.Indent--;
            }
        }

        EmitDefaultCase(indented);

        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
    }

    private static void EmitCaseHeader(IndentedTextWriter indented, InterfaceDeclaration iface, bool hasMultipleOverloads)
    {
        indented.Indent++;
        indented.WriteLine(hasMultipleOverloads
            ? $"case \"{iface.Name}\" when call.Arguments.Count == {iface.Parameters.Count}:"
            : $"case \"{iface.Name}\":");
    }

    private static void EmitServiceResolution(IndentedTextWriter indented, ImplementationInfo impl)
    {
        var shortName = impl.ClassName.Split(["::", "."], StringSplitOptions.RemoveEmptyEntries).Last();
        var localName = $"_{CamelCase(impl.ClassName)}";

        indented.WriteLine($"var {localName} = session.Get<{impl.ClassName}>();");
        indented.WriteLine(
            $"if ({localName} == null) throw new NullReferenceException(\"EasyPlayscript: {shortName} was not registered before script execution.\");");
    }

    private static void EmitSyncDispatchBody(IndentedTextWriter indented, InterfaceDeclaration iface, ImplementationInfo impl)
    {
        var argList = BuildArgList(iface);
        var localName = $"_{CamelCase(impl.ClassName)}";

        if (impl.IsAsync)
        {
            // Async impl in sync context: fire-and-forget
            indented.WriteLine($"_ = {localName}.{impl.MethodName}({argList});");
        }
        else if (iface.ReturnType == InterfaceType.Void)
        {
            indented.WriteLine($"{localName}.{impl.MethodName}({argList});");
        }
        else
        {
            indented.WriteLine($"call.Result = {localName}.{impl.MethodName}({argList});");
        }
    }

    private static void EmitAsyncDispatchBody(IndentedTextWriter indented, InterfaceDeclaration iface, ImplementationInfo impl)
    {
        var argList = BuildArgList(iface);
        var localName = $"_{CamelCase(impl.ClassName)}";

        if (impl.IsAsync)
        {
            indented.WriteLine(iface.ReturnType == InterfaceType.Void
                ? $"await {localName}.{impl.MethodName}({argList});"
                : $"call.Result = await {localName}.{impl.MethodName}({argList});");
        }
        else if (iface.ReturnType == InterfaceType.Void)
        {
            indented.WriteLine($"{localName}.{impl.MethodName}({argList});");
        }
        else
        {
            indented.WriteLine($"call.Result = {localName}.{impl.MethodName}({argList});");
        }
    }

    private static string BuildArgList(InterfaceDeclaration iface)
    {
        return string.Join(", ",
            iface.Parameters.Select((p, i) =>
                $"(({MapArgumentType(p.Type)})call.Arguments[{i}]).Value"));
    }

    private static void EmitDefaultCase(IndentedTextWriter indented)
    {
        indented.WriteLine("default:");
        indented.Indent++;
        indented.WriteLine("throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("$\"EasyPlayscript: Unhandled action '{call.Identifier}'.\");");
        indented.Indent--;
        indented.Indent--;
    }

    private static ImplementationInfo? FindMatchingImplementation(
        List<ImplementationInfo> implementations, InterfaceDeclaration iface)
    {
        return implementations.FirstOrDefault(i =>
            i.EffectiveName == iface.Name &&
            i.ParameterTypeNames.Count == iface.Parameters.Count &&
            i.IsAsync == iface.IsAsync);
    }

    private static string CamelCase(string qualifiedName)
    {
        var parts = qualifiedName.Split(["::", "."], StringSplitOptions.RemoveEmptyEntries);
        var name = parts.Last();
        if (name.Length == 0) return name;
        return char.ToLowerInvariant(name[0]) + name.Substring(1);
    }

    private static string MapArgumentType(InterfaceType type)
    {
        return type switch
        {
            InterfaceType.String => "StringArgument",
            InterfaceType.Int => "IntArgument",
            InterfaceType.Decimal => "DoubleArgument",
            InterfaceType.Bool => "BoolArgument",
            _ => "ArgumentValue"
        };
    }
}
