using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EasyPlayscript.Generator;

[Generator]
public class ScriptRegistry : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("Script.g.cs", SourceText.From(GenerateScript(), Encoding.UTF8));
            ctx.AddSource("Text.g.cs", SourceText.From(GenerateText(), Encoding.UTF8));
        });
    }

    private static string GenerateScript()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using System.Text;");
        indented.WriteLine("using System.Threading.Tasks;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.DataModel;");
        indented.WriteLine("using EasyPlayscript.Runtime;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class Script");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine("public ScriptBlock Block { get; set; } = default!;");
        indented.WriteLine();
        indented.WriteLine("internal PlayscriptRuntimeSession? Runtime { get; set; }");
        indented.WriteLine();
        indented.WriteLine("private ScriptNavigator? _navigator;");
        indented.WriteLine("private ScriptNavigator Navigator => _navigator ??= new ScriptNavigator(Block);");
        indented.WriteLine();

        indented.WriteLine("public ScriptPointer Pointer => Navigator.Pointer;");
        indented.WriteLine();
        indented.WriteLine("public void JumpTo(ScriptPointer pointer) => Navigator.JumpTo(pointer);");
        indented.WriteLine();
        indented.WriteLine("public void Reset() => Navigator.Reset();");
        indented.WriteLine();
        indented.WriteLine("public bool IsLastLineOfParagraph => Navigator.IsLastLineOfParagraph;");
        indented.WriteLine("public bool IsLastParagraphOfPage => Navigator.IsLastParagraphOfPage;");
        indented.WriteLine("public bool IsLastPage => Navigator.IsLastPage;");
        indented.WriteLine("public bool IsLastLineOfPage => Navigator.IsLastLineOfPage;");
        indented.WriteLine("public bool IsLastLineOfScript => Navigator.IsLastLineOfScript;");
        indented.WriteLine("public bool IsLastParagraphOfScript => Navigator.IsLastParagraphOfScript;");
        indented.WriteLine("public bool IsLastSegmentOfLine => Navigator.IsLastSegmentOfLine;");
        indented.WriteLine("public bool IsLastSegmentOfParagraph => Navigator.IsLastSegmentOfParagraph;");
        indented.WriteLine("public bool IsLastSegmentOfPage => Navigator.IsLastSegmentOfPage;");
        indented.WriteLine("public bool IsLastSegmentOfScript => Navigator.IsLastSegmentOfScript;");
        indented.WriteLine();

        // ── RenderSegment helper ──
        EmitRenderSegment(indented, "RenderSegment", "Segment", false);
        indented.WriteLine();
        EmitRenderSegment(indented, "RenderSegmentAsync", "Segment", true);
        indented.WriteLine();

        // ── RenderLine helper (concatenates segments) ──
        EmitRenderLine(indented, "RenderLine", "RenderSegment", false);
        indented.WriteLine();
        EmitRenderLine(indented, "RenderLineAsync", "RenderSegmentAsync", true);
        indented.WriteLine();

        // ── RenderNextLineSegment (sync) ──
        EmitRenderNextMethod(indented, "SegmentRenderResult", "RenderNextLineSegment",
            "Navigator.RenderNextLineSegment(RenderSegment)", false);
        indented.WriteLine();

        // ── RenderNextLineSegment (async) ──
        EmitRenderNextMethod(indented, "SegmentRenderResult", "RenderNextLineSegmentAsync",
            "await Navigator.RenderNextLineSegmentAsync(RenderSegmentAsync)", true);
        indented.WriteLine();

        // ── RenderNextLine (sync) ──
        EmitRenderNextMethod(indented, "LineRenderResult", "RenderNextLine",
            "Navigator.RenderNextLine(RenderLine)", false);
        indented.WriteLine();

        // ── RenderNextLine (async) ──
        EmitRenderNextMethod(indented, "LineRenderResult", "RenderNextLineAsync",
            "await Navigator.RenderNextLineAsync(RenderLineAsync)", true);
        indented.WriteLine();

        // ── RenderNextParagraph (sync) ──
        EmitRenderNextMethod(indented, "ParagraphRenderResult", "RenderNextParagraph",
            "Navigator.RenderNextParagraph(RenderLine)", false);
        indented.WriteLine();

        // ── RenderNextParagraph (async) ──
        EmitRenderNextMethod(indented, "ParagraphRenderResult", "RenderNextParagraphAsync",
            "await Navigator.RenderNextParagraphAsync(RenderLineAsync)", true);
        indented.WriteLine();

        // ── RenderNextPage (sync) ──
        EmitRenderNextMethod(indented, "PageRenderResult", "RenderNextPage",
            "Navigator.RenderNextPage(RenderLine)", false);
        indented.WriteLine();

        // ── RenderNextPage (async) ──
        EmitRenderNextMethod(indented, "PageRenderResult", "RenderNextPageAsync",
            "await Navigator.RenderNextPageAsync(RenderLineAsync)", true);
        indented.WriteLine();

        // ── Run (sync) ──
        indented.WriteLine("public void Run()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (Runtime == null) throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("\"Script.Run() requires a PlayscriptRuntimeSession. Use session.GetScript() to create session-aware scripts.\");");
        indented.Indent--;
        indented.WriteLine("foreach (var page in Block.Pages)");
        indented.Indent++;
        indented.WriteLine("foreach (var paragraph in page.Paragraphs)");
        indented.Indent++;
        indented.WriteLine("foreach (var line in paragraph.Lines)");
        indented.Indent++;
        indented.WriteLine("foreach (var segment in line.Segments)");
        indented.Indent++;
        indented.WriteLine("foreach (var item in segment.Items)");
        indented.Indent++;
        indented.WriteLine("if (item is ConsumerCallItem call)");
        indented.Indent++;
        indented.WriteLine("Runtime.DispatchCall(call);");
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        // ── RunAsync (async) ──
        indented.WriteLine("public async Task RunAsync()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (Runtime == null) throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("\"Script.RunAsync() requires a PlayscriptRuntimeSession. Use session.GetScript() to create session-aware scripts.\");");
        indented.Indent--;
        indented.WriteLine("foreach (var page in Block.Pages)");
        indented.Indent++;
        indented.WriteLine("foreach (var paragraph in page.Paragraphs)");
        indented.Indent++;
        indented.WriteLine("foreach (var line in paragraph.Lines)");
        indented.Indent++;
        indented.WriteLine("foreach (var segment in line.Segments)");
        indented.Indent++;
        indented.WriteLine("foreach (var item in segment.Items)");
        indented.Indent++;
        indented.WriteLine("if (item is ConsumerCallItem call)");
        indented.Indent++;
        indented.WriteLine("await Runtime.DispatchCallAsync(call);");
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static void EmitRenderSegment(IndentedTextWriter indented, string methodName, string paramType, bool isAsync)
    {
        var asyncKeyword = isAsync ? "async Task<string>" : "string";
        var awaitKeyword = isAsync ? "await " : "";
        var runtimeCheck = isAsync
            ? $"\"Script.{methodName}() requires a PlayscriptRuntimeSession. Use session.GetScript() to create session-aware scripts.\""
            : $"\"Script.{methodName}() requires a PlayscriptRuntimeSession. Use session.GetScript() to create session-aware scripts.\"";

        indented.WriteLine($"private {asyncKeyword} {methodName}({paramType} segment)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("var sb = new StringBuilder();");
        indented.WriteLine("foreach (var item in segment.Items)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (item)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("case TextItem textItem:");
        indented.Indent++;
        indented.WriteLine("sb.Append(textItem.Text);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.WriteLine("case ConsumerCallItem call:");
        indented.Indent++;
        indented.WriteLine("if (Runtime == null) throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine(runtimeCheck + ");");
        indented.Indent--;
        indented.WriteLine($"{awaitKeyword}Runtime.DispatchCall{(isAsync ? "Async" : "")}(call);");
        indented.WriteLine("if (call.Result != null) sb.Append(call.Result);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine("return sb.ToString();");
        indented.Indent--;
        indented.WriteLine("}");
    }

    private static void EmitRenderLine(IndentedTextWriter indented, string methodName, string renderSegmentMethod, bool isAsync)
    {
        var asyncKeyword = isAsync ? "async Task<string>" : "string";
        var awaitKeyword = isAsync ? "await " : "";

        indented.WriteLine($"private {asyncKeyword} {methodName}(Line line)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("var sb = new StringBuilder();");
        indented.WriteLine("foreach (var segment in line.Segments)");
        indented.Indent++;
        indented.WriteLine($"sb.Append({awaitKeyword}{renderSegmentMethod}(segment));");
        indented.Indent--;
        indented.WriteLine("return sb.ToString();");
        indented.Indent--;
        indented.WriteLine("}");
    }

    private static void EmitRenderNextMethod(IndentedTextWriter indented, string returnType, string methodName, string delegateCall, bool isAsync)
    {
        var asyncKeyword = isAsync ? $"async Task<{returnType}?> " : $"{returnType}? ";
        var awaitPrefix = isAsync ? "await " : "";

        indented.WriteLine($"public {asyncKeyword}{methodName}()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (Runtime == null) throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine($"\"Script.{methodName}() requires a PlayscriptRuntimeSession. Use session.GetScript() to create session-aware scripts.\");");
        indented.Indent--;
        indented.WriteLine($"return {awaitPrefix}{delegateCall};");
        indented.Indent--;
        indented.WriteLine("}");
    }

    private static string GenerateText()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using System;");
        indented.WriteLine("using System.Text;");
        indented.WriteLine("using System.Threading.Tasks;");
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.DataModel;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class Text");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public TextBlock Block { get; set; } = default!;");
        indented.WriteLine();
        indented.WriteLine("internal PlayscriptRuntimeSession? Runtime { get; set; }");
        indented.WriteLine();

        // ── Render (sync) ──
        indented.WriteLine("public string Render(PlayscriptRegistry registry, PlayscriptRuntimeSession session)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("var sb = new StringBuilder();");
        indented.WriteLine("foreach (var line in Block.Lines)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (sb.Length > 0) sb.AppendLine();");
        indented.WriteLine("foreach (var segment in line.Segments)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("foreach (var item in segment.Items)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (item)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("case TextItem textItem:");
        indented.Indent++;
        indented.WriteLine("sb.Append(textItem.Text);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.WriteLine("case ConsumerCallItem call:");
        indented.Indent++;
        indented.WriteLine("registry.DispatchCall(call, session);");
        indented.WriteLine("if (call.Result != null) sb.Append(call.Result);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine("return sb.ToString();");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();
        indented.WriteLine(
            "public string Render(PlayscriptRuntimeSession session) => Render(session.Registry, session);");
        indented.WriteLine();
        indented.WriteLine("public string Render()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (Runtime == null) throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("\"Text.Render() requires a PlayscriptRuntimeSession. Use session.GetText() to create session-aware texts.\");");
        indented.Indent--;
        indented.WriteLine("return Render(Runtime.Registry, Runtime);");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();

        // ── RenderAsync (async) ──
        indented.WriteLine("public async Task<string> RenderAsync(PlayscriptRegistry registry, PlayscriptRuntimeSession session)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("var sb = new StringBuilder();");
        indented.WriteLine("foreach (var line in Block.Lines)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (sb.Length > 0) sb.AppendLine();");
        indented.WriteLine("foreach (var segment in line.Segments)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("foreach (var item in segment.Items)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (item)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("case TextItem textItem:");
        indented.Indent++;
        indented.WriteLine("sb.Append(textItem.Text);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.WriteLine("case ConsumerCallItem call:");
        indented.Indent++;
        indented.WriteLine("await registry.DispatchCallAsync(call, session);");
        indented.WriteLine("if (call.Result != null) sb.Append(call.Result);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine("return sb.ToString();");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();
        indented.WriteLine(
            "public async Task<string> RenderAsync(PlayscriptRuntimeSession session) => await RenderAsync(session.Registry, session);");
        indented.WriteLine();
        indented.WriteLine("public async Task<string> RenderAsync()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (Runtime == null) throw new InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("\"Text.RenderAsync() requires a PlayscriptRuntimeSession. Use session.GetText() to create session-aware texts.\");");
        indented.Indent--;
        indented.WriteLine("return await RenderAsync(Runtime.Registry, Runtime);");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }
}
