using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace EasyPlayscript.Generator;

/// <summary>
///     Source generator that emits data classes (<c>Script</c>, <c>Text</c>)
///     via <see cref="IncrementalGeneratorInitializationContext.RegisterPostInitializationOutput" /> into the
///     <c>EasyPlayscript.Generated</c> namespace.
/// </summary>
[Generator]
public class ScriptRegistry : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
        {
            ctx.AddSource("Script.g.cs", SourceText.From(GenerateScript(), Encoding.UTF8));
            ctx.AddSource("Text.g.cs", SourceText.From(GenerateText(), Encoding.UTF8));
        });
    }

    private static string GenerateScript()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class Script");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public ScriptBlock Block { get; set; } = default!;");
        indented.WriteLine();
        indented.WriteLine("internal PlayscriptRuntime? Runtime { get; set; }");
        indented.WriteLine();
        indented.WriteLine("public void Run()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (Runtime == null) throw new System.InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("\"Script.Run() requires a PlayscriptRuntime. Use runtime.GetScript() to create runtime-aware scripts.\");");
        indented.Indent--;
        indented.WriteLine("foreach (var page in Block.Pages)");
        indented.Indent++;
        indented.WriteLine("foreach (var paragraph in page.Paragraphs)");
        indented.Indent++;
        indented.WriteLine("foreach (var line in paragraph.Lines)");
        indented.Indent++;
        indented.WriteLine("foreach (var item in line.Items)");
        indented.Indent++;
        indented.WriteLine("if (item is ConsumerCallItem call)");
        indented.Indent++;
        indented.WriteLine("Runtime.DispatchCall(call);");
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string GenerateText()
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine("#nullable enable");
        indented.WriteLine();
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine();
        indented.WriteLine("namespace EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public class Text");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public TextBlock Block { get; set; } = default!;");
        indented.WriteLine();
        indented.WriteLine("internal PlayscriptRuntime? Runtime { get; set; }");
        indented.WriteLine();
        indented.WriteLine("public string Render(PlayscriptRegistry registry, TransientNodeContext context)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("var sb = new System.Text.StringBuilder();");
        indented.WriteLine("foreach (var line in Block.Lines)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (sb.Length > 0) sb.AppendLine();");
        indented.WriteLine("foreach (var item in line.Items)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("switch (item)");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("case TextItem textItem:");
        indented.Indent++;
        indented.WriteLine("sb.Append(textItem.Text);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.WriteLine("case ConsumerCallItem call:");
        indented.Indent++;
        indented.WriteLine("registry.DispatchCall(call, context);");
        indented.WriteLine("if (call.Result != null) sb.Append(call.Result);");
        indented.WriteLine("break;");
        indented.Indent--;
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine("return sb.ToString();");
        indented.Indent--;
        indented.WriteLine("}");
        indented.WriteLine();
        indented.WriteLine(
            "public string Render(PlayscriptRuntime runtime, TransientNodeContext? sceneContext = null) => Render(runtime.Registry, sceneContext ?? new TransientNodeContext());");
        indented.WriteLine();
        indented.WriteLine("public string Render()");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("if (Runtime == null) throw new System.InvalidOperationException(");
        indented.Indent++;
        indented.WriteLine("\"Text.Render() requires a PlayscriptRuntime. Use runtime.GetText() to create runtime-aware texts.\");");
        indented.Indent--;
        indented.WriteLine("return Render(Runtime.Registry, Runtime.SceneContext);");
        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }
}