<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>

        <IsPackable>true</IsPackable>
        <PackageId>EasyPlayscript.BuildTask</PackageId>
        <Version>1.0.0-preview1</Version>
        <Authors>EasyPlayscript</Authors>
        <Description>MSBuild task for compiling EasyPlayscript .scpt files</Description>
        <BuildOutputTargetFolder>tools</BuildOutputTargetFolder>
        <SuppressDependenciesWhenPacking>false</SuppressDependenciesWhenPacking>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\EasyPlayscript.Core\EasyPlayscript.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="JetBrains.Annotations" Version="2026.2.0"/>
        <PackageReference Include="Microsoft.Build.Utilities.Core" Version="18.7.1" PrivateAssets="all"/>
        <PackageReference Include="Microsoft.AspNetCore.Cryptography.KeyDerivation" Version="10.0.10"/>
    </ItemGroup>

    <ItemGroup>
        <None Include="build\*.targets" Pack="true" PackagePath="build\"/>
        <None Include="build\*.targets" Pack="true" PackagePath="buildTransitive\"/>
        <None Include="$(OutputPath)\EasyPlayscript.Core.dll" Pack="true" PackagePath="tools/netstandard2.0/" Visible="false"/>
        <None Include="$(OutputPath)\Antlr4.Runtime.Standard.dll" Pack="true" PackagePath="tools/netstandard2.0/" Visible="false"/>
        <None Include="$(OutputPath)\MessagePack.dll" Pack="true" PackagePath="tools/netstandard2.0/" Visible="false"/>
        <None Include="$(OutputPath)\MessagePack.Annotations.dll" Pack="true" PackagePath="tools/netstandard2.0/" Visible="false"/>
        <None Include="$(OutputPath)\Microsoft.AspNetCore.Cryptography.KeyDerivation.dll" Pack="true" PackagePath="tools/netstandard2.0/" Visible="false"/>
        <None Include="$(OutputPath)\Microsoft.AspNetCore.Cryptography.Internal.dll" Pack="true" PackagePath="tools/netstandard2.0/" Visible="false"/>
    </ItemGroup>

</Project>
