using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace EasyPlayscript.Parsing;

public static class RegistryEmitter
{
    public static string Generate(Dictionary<string, ScriptBlock> scripts,
        Dictionary<string, ScriptBlock> texts, string outputPath, string aesKey)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine("public static class Registry");
        indented.WriteLine("{");
        indented.Indent++;

        indented.WriteLine(
            "private static readonly System.Lazy<System.Collections.Generic.Dictionary<string, ScriptBlock>> _scripts =");
        indented.Indent++;
        indented.WriteLine($"new(() => PlayscriptLoader.LoadScripts(\"{outputPath}\", \"{aesKey}\"));");
        indented.Indent--;
        indented.WriteLine();
        indented.WriteLine(
            "private static readonly System.Lazy<System.Collections.Generic.Dictionary<string, ScriptBlock>> _texts =");
        indented.Indent++;
        indented.WriteLine($"new(() => PlayscriptLoader.LoadTexts(\"{outputPath}\", \"{aesKey}\"));");
        indented.Indent--;
        indented.WriteLine();

        var sortedScripts = scripts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal);
        foreach (var kvp in sortedScripts)
        {
            var propName = ToScreamingSnakeCase(kvp.Key);
            indented.WriteLine(
                $"public static Script {propName} => new Script {{ Block = _scripts.Value[\"{kvp.Key}\"] }};");
        }

        var sortedTexts = texts.OrderBy(kvp => kvp.Key, StringComparer.Ordinal);
        foreach (var kvp in sortedTexts)
        {
            var propName = ToScreamingSnakeCase(kvp.Key);
            indented.WriteLine($"public static Text {propName} => new Text {{ Block = _texts.Value[\"{kvp.Key}\"] }};");
        }

        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    private static string ToScreamingSnakeCase(string name)
    {
        var sb = new StringBuilder();
        foreach (var c in name)
        {
            sb.Append(c is ' ' or '-' ? '_' : char.ToUpperInvariant(c));
        }

        return sb.ToString();
    }
}
