//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Myriad-s-Projects/EasyPlayscript/EasyPlayscript.Core/core/playscript/definition/PlayscriptContentLexer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class PlayscriptContentLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		AT=1, COMMENT=2, LPAREN=3, RPAREN=4, STRING_LITERAL=5, IDENTIFIER=6, COMMA=7, 
		INTEGER_LITERAL=8, FLOAT_LITERAL=9, BOOLEAN_LITERAL=10, PLUS=11, DOT=12, 
		BLANK_LINE=13, SINGLE_NEWLINE=14, SLASH=15, TEXT=16, C_WS=17, S_PLUS=18, 
		C_LPAREN=19, C_RPAREN=20, C_DOT=21, C_COMMA=22;
	public const int
		IN_CALL=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "IN_CALL"
	};

	public static readonly string[] ruleNames = {
		"S_AT", "S_PLUS", "S_COMMENT", "BLANK_LINE", "SINGLE_NEWLINE", "SLASH", 
		"TEXT", "C_LPAREN", "C_RPAREN", "C_STRING_LITERAL", "C_FLOAT_LITERAL", 
		"C_INTEGER_LITERAL", "C_BOOLEAN_LITERAL", "C_DOT", "C_IDENTIFIER", "C_COMMA", 
		"C_WS"
	};


	public PlayscriptContentLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PlayscriptContentLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "'/'", null, null, "'+'", "'('", "')'", "'.'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "AT", "COMMENT", "LPAREN", "RPAREN", "STRING_LITERAL", "IDENTIFIER", 
		"COMMA", "INTEGER_LITERAL", "FLOAT_LITERAL", "BOOLEAN_LITERAL", "PLUS", 
		"DOT", "BLANK_LINE", "SINGLE_NEWLINE", "SLASH", "TEXT", "C_WS", "S_PLUS", 
		"C_LPAREN", "C_RPAREN", "C_DOT", "C_COMMA"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlayscriptContentLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlayscriptContentLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,22,191,6,-1,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,
		6,7,6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,
		2,14,7,14,2,15,7,15,2,16,7,16,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,2,
		1,2,5,2,48,8,2,10,2,12,2,51,9,2,1,2,1,2,1,2,1,3,3,3,57,8,3,1,3,1,3,5,3,
		61,8,3,10,3,12,3,64,9,3,1,3,3,3,67,8,3,1,3,1,3,1,4,3,4,72,8,4,1,4,1,4,
		1,5,1,5,1,6,1,6,1,6,4,6,81,8,6,11,6,12,6,82,1,7,1,7,1,7,1,7,1,8,1,8,1,
		8,1,8,1,8,1,9,1,9,1,9,1,9,5,9,98,8,9,10,9,12,9,101,9,9,1,9,1,9,1,9,1,9,
		1,10,3,10,108,8,10,1,10,4,10,111,8,10,11,10,12,10,112,1,10,1,10,4,10,117,
		8,10,11,10,12,10,118,1,10,1,10,3,10,123,8,10,1,10,4,10,126,8,10,11,10,
		12,10,127,3,10,130,8,10,1,10,1,10,3,10,134,8,10,1,10,4,10,137,8,10,11,
		10,12,10,138,3,10,141,8,10,1,10,1,10,1,11,3,11,146,8,11,1,11,4,11,149,
		8,11,11,11,12,11,150,1,11,1,11,1,12,1,12,1,12,1,12,1,12,1,12,1,12,1,12,
		1,12,3,12,164,8,12,1,12,1,12,1,13,1,13,1,13,1,13,1,14,1,14,5,14,174,8,
		14,10,14,12,14,177,9,14,1,14,1,14,1,15,1,15,1,15,1,15,1,16,4,16,186,8,
		16,11,16,12,16,187,1,16,1,16,0,0,17,2,0,4,18,6,0,8,13,10,14,12,15,14,16,
		16,19,18,20,20,0,22,0,24,0,26,0,28,21,30,0,32,22,34,17,2,0,1,8,2,0,10,
		10,13,13,2,0,9,9,32,32,7,0,10,10,13,13,35,35,43,43,47,47,64,64,92,92,4,
		0,10,10,13,13,34,34,92,92,1,0,48,57,2,0,69,69,101,101,3,0,65,90,95,95,
		97,122,4,0,48,57,65,90,95,95,97,122,212,0,2,1,0,0,0,0,4,1,0,0,0,0,6,1,
		0,0,0,0,8,1,0,0,0,0,10,1,0,0,0,0,12,1,0,0,0,0,14,1,0,0,0,1,16,1,0,0,0,
		1,18,1,0,0,0,1,20,1,0,0,0,1,22,1,0,0,0,1,24,1,0,0,0,1,26,1,0,0,0,1,28,
		1,0,0,0,1,30,1,0,0,0,1,32,1,0,0,0,1,34,1,0,0,0,2,36,1,0,0,0,4,41,1,0,0,
		0,6,45,1,0,0,0,8,56,1,0,0,0,10,71,1,0,0,0,12,75,1,0,0,0,14,80,1,0,0,0,
		16,84,1,0,0,0,18,88,1,0,0,0,20,93,1,0,0,0,22,107,1,0,0,0,24,145,1,0,0,
		0,26,163,1,0,0,0,28,167,1,0,0,0,30,171,1,0,0,0,32,180,1,0,0,0,34,185,1,
		0,0,0,36,37,5,64,0,0,37,38,1,0,0,0,38,39,6,0,0,0,39,40,6,0,1,0,40,3,1,
		0,0,0,41,42,5,43,0,0,42,43,1,0,0,0,43,44,6,1,2,0,44,5,1,0,0,0,45,49,5,
		35,0,0,46,48,8,0,0,0,47,46,1,0,0,0,48,51,1,0,0,0,49,47,1,0,0,0,49,50,1,
		0,0,0,50,52,1,0,0,0,51,49,1,0,0,0,52,53,6,2,3,0,53,54,6,2,4,0,54,7,1,0,
		0,0,55,57,5,13,0,0,56,55,1,0,0,0,56,57,1,0,0,0,57,58,1,0,0,0,58,62,5,10,
		0,0,59,61,7,1,0,0,60,59,1,0,0,0,61,64,1,0,0,0,62,60,1,0,0,0,62,63,1,0,
		0,0,63,66,1,0,0,0,64,62,1,0,0,0,65,67,5,13,0,0,66,65,1,0,0,0,66,67,1,0,
		0,0,67,68,1,0,0,0,68,69,5,10,0,0,69,9,1,0,0,0,70,72,5,13,0,0,71,70,1,0,
		0,0,71,72,1,0,0,0,72,73,1,0,0,0,73,74,5,10,0,0,74,11,1,0,0,0,75,76,5,47,
		0,0,76,13,1,0,0,0,77,78,5,92,0,0,78,81,8,0,0,0,79,81,8,2,0,0,80,77,1,0,
		0,0,80,79,1,0,0,0,81,82,1,0,0,0,82,80,1,0,0,0,82,83,1,0,0,0,83,15,1,0,
		0,0,84,85,5,40,0,0,85,86,1,0,0,0,86,87,6,7,5,0,87,17,1,0,0,0,88,89,5,41,
		0,0,89,90,1,0,0,0,90,91,6,8,6,0,91,92,6,8,7,0,92,19,1,0,0,0,93,99,5,34,
		0,0,94,98,8,3,0,0,95,96,5,92,0,0,96,98,9,0,0,0,97,94,1,0,0,0,97,95,1,0,
		0,0,98,101,1,0,0,0,99,97,1,0,0,0,99,100,1,0,0,0,100,102,1,0,0,0,101,99,
		1,0,0,0,102,103,5,34,0,0,103,104,1,0,0,0,104,105,6,9,8,0,105,21,1,0,0,
		0,106,108,5,45,0,0,107,106,1,0,0,0,107,108,1,0,0,0,108,110,1,0,0,0,109,
		111,7,4,0,0,110,109,1,0,0,0,111,112,1,0,0,0,112,110,1,0,0,0,112,113,1,
		0,0,0,113,140,1,0,0,0,114,116,5,46,0,0,115,117,7,4,0,0,116,115,1,0,0,0,
		117,118,1,0,0,0,118,116,1,0,0,0,118,119,1,0,0,0,119,129,1,0,0,0,120,122,
		7,5,0,0,121,123,5,45,0,0,122,121,1,0,0,0,122,123,1,0,0,0,123,125,1,0,0,
		0,124,126,7,4,0,0,125,124,1,0,0,0,126,127,1,0,0,0,127,125,1,0,0,0,127,
		128,1,0,0,0,128,130,1,0,0,0,129,120,1,0,0,0,129,130,1,0,0,0,130,141,1,
		0,0,0,131,133,7,5,0,0,132,134,5,45,0,0,133,132,1,0,0,0,133,134,1,0,0,0,
		134,136,1,0,0,0,135,137,7,4,0,0,136,135,1,0,0,0,137,138,1,0,0,0,138,136,
		1,0,0,0,138,139,1,0,0,0,139,141,1,0,0,0,140,114,1,0,0,0,140,131,1,0,0,
		0,141,142,1,0,0,0,142,143,6,10,9,0,143,23,1,0,0,0,144,146,5,45,0,0,145,
		144,1,0,0,0,145,146,1,0,0,0,146,148,1,0,0,0,147,149,7,4,0,0,148,147,1,
		0,0,0,149,150,1,0,0,0,150,148,1,0,0,0,150,151,1,0,0,0,151,152,1,0,0,0,
		152,153,6,11,10,0,153,25,1,0,0,0,154,155,5,116,0,0,155,156,5,114,0,0,156,
		157,5,117,0,0,157,164,5,101,0,0,158,159,5,102,0,0,159,160,5,97,0,0,160,
		161,5,108,0,0,161,162,5,115,0,0,162,164,5,101,0,0,163,154,1,0,0,0,163,
		158,1,0,0,0,164,165,1,0,0,0,165,166,6,12,11,0,166,27,1,0,0,0,167,168,5,
		46,0,0,168,169,1,0,0,0,169,170,6,13,12,0,170,29,1,0,0,0,171,175,7,6,0,
		0,172,174,7,7,0,0,173,172,1,0,0,0,174,177,1,0,0,0,175,173,1,0,0,0,175,
		176,1,0,0,0,176,178,1,0,0,0,177,175,1,0,0,0,178,179,6,14,13,0,179,31,1,
		0,0,0,180,181,5,44,0,0,181,182,1,0,0,0,182,183,6,15,14,0,183,33,1,0,0,
		0,184,186,7,1,0,0,185,184,1,0,0,0,186,187,1,0,0,0,187,185,1,0,0,0,187,
		188,1,0,0,0,188,189,1,0,0,0,189,190,6,16,15,0,190,35,1,0,0,0,25,0,1,49,
		56,62,66,71,80,82,97,99,107,112,118,122,127,129,133,138,140,145,150,163,
		175,187,16,7,1,0,5,1,0,7,11,0,7,2,0,0,1,0,7,3,0,7,4,0,4,0,0,7,5,0,7,9,
		0,7,8,0,7,10,0,7,12,0,7,6,0,7,7,0,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
