//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyPlayscript/EasyPlayscript.Core/core/playscript/definition/PlayscriptContentParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class PlayscriptContentParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		AT=1, COMMENT=2, LPAREN=3, RPAREN=4, STRING_LITERAL=5, IDENTIFIER=6, COMMA=7, 
		INTEGER_LITERAL=8, FLOAT_LITERAL=9, BOOLEAN_LITERAL=10, BLANK_LINE=11, 
		SINGLE_NEWLINE=12, SLASH=13, TEXT=14, C_WS=15, C_LPAREN=16, C_RPAREN=17, 
		C_COMMA=18;
	public const int
		RULE_scriptContent = 0, RULE_textContent = 1, RULE_page = 2, RULE_paragraph = 3, 
		RULE_line = 4, RULE_textParagraph = 5, RULE_textLine = 6, RULE_pageBreak = 7, 
		RULE_consumerCall = 8, RULE_argument = 9;
	public static readonly string[] ruleNames = {
		"scriptContent", "textContent", "page", "paragraph", "line", "textParagraph", 
		"textLine", "pageBreak", "consumerCall", "argument"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "'/'", null, null, "'('", "')'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "AT", "COMMENT", "LPAREN", "RPAREN", "STRING_LITERAL", "IDENTIFIER", 
		"COMMA", "INTEGER_LITERAL", "FLOAT_LITERAL", "BOOLEAN_LITERAL", "BLANK_LINE", 
		"SINGLE_NEWLINE", "SLASH", "TEXT", "C_WS", "C_LPAREN", "C_RPAREN", "C_COMMA"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlayscriptContentParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlayscriptContentParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PlayscriptContentParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PlayscriptContentParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ScriptContentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PageContext[] page() {
			return GetRuleContexts<PageContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PageContext page(int i) {
			return GetRuleContext<PageContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(PlayscriptContentParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PageBreakContext[] pageBreak() {
			return GetRuleContexts<PageBreakContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PageBreakContext pageBreak(int i) {
			return GetRuleContext<PageBreakContext>(i);
		}
		public ScriptContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scriptContent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScriptContent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContentContext scriptContent() {
		ScriptContentContext _localctx = new ScriptContentContext(Context, State);
		EnterRule(_localctx, 0, RULE_scriptContent);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 20;
			page();
			State = 26;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 14336L) != 0)) {
				{
				{
				State = 21;
				pageBreak();
				State = 22;
				page();
				}
				}
				State = 28;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 29;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextParagraphContext[] textParagraph() {
			return GetRuleContexts<TextParagraphContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TextParagraphContext textParagraph(int i) {
			return GetRuleContext<TextParagraphContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(PlayscriptContentParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] BLANK_LINE() { return GetTokens(PlayscriptContentParser.BLANK_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLANK_LINE(int i) {
			return GetToken(PlayscriptContentParser.BLANK_LINE, i);
		}
		public TextContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textContent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextContent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextContentContext textContent() {
		TextContentContext _localctx = new TextContentContext(Context, State);
		EnterRule(_localctx, 2, RULE_textContent);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 31;
			textParagraph();
			State = 36;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==BLANK_LINE) {
				{
				{
				State = 32;
				Match(BLANK_LINE);
				State = 33;
				textParagraph();
				}
				}
				State = 38;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 39;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PageContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ParagraphContext[] paragraph() {
			return GetRuleContexts<ParagraphContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ParagraphContext paragraph(int i) {
			return GetRuleContext<ParagraphContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] BLANK_LINE() { return GetTokens(PlayscriptContentParser.BLANK_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLANK_LINE(int i) {
			return GetToken(PlayscriptContentParser.BLANK_LINE, i);
		}
		public PageContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_page; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPage(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PageContext page() {
		PageContext _localctx = new PageContext(Context, State);
		EnterRule(_localctx, 4, RULE_page);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 41;
			paragraph();
			State = 46;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 42;
					Match(BLANK_LINE);
					State = 43;
					paragraph();
					}
					} 
				}
				State = 48;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParagraphContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SINGLE_NEWLINE() { return GetTokens(PlayscriptContentParser.SINGLE_NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_NEWLINE(int i) {
			return GetToken(PlayscriptContentParser.SINGLE_NEWLINE, i);
		}
		public ParagraphContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_paragraph; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParagraph(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParagraphContext paragraph() {
		ParagraphContext _localctx = new ParagraphContext(Context, State);
		EnterRule(_localctx, 6, RULE_paragraph);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 49;
			line();
			State = 54;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 50;
					Match(SINGLE_NEWLINE);
					State = 51;
					line();
					}
					} 
				}
				State = 56;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] TEXT() { return GetTokens(PlayscriptContentParser.TEXT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TEXT(int i) {
			return GetToken(PlayscriptContentParser.TEXT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConsumerCallContext[] consumerCall() {
			return GetRuleContexts<ConsumerCallContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConsumerCallContext consumerCall(int i) {
			return GetRuleContext<ConsumerCallContext>(i);
		}
		public LineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_line; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LineContext line() {
		LineContext _localctx = new LineContext(Context, State);
		EnterRule(_localctx, 8, RULE_line);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 59;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 59;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case TEXT:
					{
					State = 57;
					Match(TEXT);
					}
					break;
				case AT:
					{
					State = 58;
					consumerCall();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 61;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==AT || _la==TEXT );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextParagraphContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextLineContext[] textLine() {
			return GetRuleContexts<TextLineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TextLineContext textLine(int i) {
			return GetRuleContext<TextLineContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SINGLE_NEWLINE() { return GetTokens(PlayscriptContentParser.SINGLE_NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_NEWLINE(int i) {
			return GetToken(PlayscriptContentParser.SINGLE_NEWLINE, i);
		}
		public TextParagraphContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textParagraph; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextParagraph(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextParagraphContext textParagraph() {
		TextParagraphContext _localctx = new TextParagraphContext(Context, State);
		EnterRule(_localctx, 10, RULE_textParagraph);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 63;
			textLine();
			State = 68;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SINGLE_NEWLINE) {
				{
				{
				State = 64;
				Match(SINGLE_NEWLINE);
				State = 65;
				textLine();
				}
				}
				State = 70;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextLineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] TEXT() { return GetTokens(PlayscriptContentParser.TEXT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TEXT(int i) {
			return GetToken(PlayscriptContentParser.TEXT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SLASH() { return GetTokens(PlayscriptContentParser.SLASH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH(int i) {
			return GetToken(PlayscriptContentParser.SLASH, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConsumerCallContext[] consumerCall() {
			return GetRuleContexts<ConsumerCallContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConsumerCallContext consumerCall(int i) {
			return GetRuleContext<ConsumerCallContext>(i);
		}
		public TextLineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textLine; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextLine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextLineContext textLine() {
		TextLineContext _localctx = new TextLineContext(Context, State);
		EnterRule(_localctx, 12, RULE_textLine);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 74;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 74;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case TEXT:
					{
					State = 71;
					Match(TEXT);
					}
					break;
				case SLASH:
					{
					State = 72;
					Match(SLASH);
					}
					break;
				case AT:
					{
					State = 73;
					consumerCall();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 76;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 24578L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PageBreakContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH() { return GetToken(PlayscriptContentParser.SLASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SINGLE_NEWLINE() { return GetTokens(PlayscriptContentParser.SINGLE_NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_NEWLINE(int i) {
			return GetToken(PlayscriptContentParser.SINGLE_NEWLINE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] BLANK_LINE() { return GetTokens(PlayscriptContentParser.BLANK_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLANK_LINE(int i) {
			return GetToken(PlayscriptContentParser.BLANK_LINE, i);
		}
		public PageBreakContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pageBreak; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPageBreak(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PageBreakContext pageBreak() {
		PageBreakContext _localctx = new PageBreakContext(Context, State);
		EnterRule(_localctx, 14, RULE_pageBreak);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 81;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==BLANK_LINE || _la==SINGLE_NEWLINE) {
				{
				{
				State = 78;
				_la = TokenStream.LA(1);
				if ( !(_la==BLANK_LINE || _la==SINGLE_NEWLINE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 83;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 84;
			Match(SLASH);
			State = 88;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==BLANK_LINE || _la==SINGLE_NEWLINE) {
				{
				{
				State = 85;
				_la = TokenStream.LA(1);
				if ( !(_la==BLANK_LINE || _la==SINGLE_NEWLINE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 90;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConsumerCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT() { return GetToken(PlayscriptContentParser.AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER() { return GetToken(PlayscriptContentParser.IDENTIFIER, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(PlayscriptContentParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(PlayscriptContentParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext[] argument() {
			return GetRuleContexts<ArgumentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument(int i) {
			return GetRuleContext<ArgumentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(PlayscriptContentParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(PlayscriptContentParser.COMMA, i);
		}
		public ConsumerCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_consumerCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConsumerCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConsumerCallContext consumerCall() {
		ConsumerCallContext _localctx = new ConsumerCallContext(Context, State);
		EnterRule(_localctx, 16, RULE_consumerCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 91;
			Match(AT);
			State = 92;
			Match(IDENTIFIER);
			State = 93;
			Match(LPAREN);
			State = 102;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1824L) != 0)) {
				{
				State = 94;
				argument();
				State = 99;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 95;
					Match(COMMA);
					State = 96;
					argument();
					}
					}
					State = 101;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 104;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(PlayscriptContentParser.STRING_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTEGER_LITERAL() { return GetToken(PlayscriptContentParser.INTEGER_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_LITERAL() { return GetToken(PlayscriptContentParser.FLOAT_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN_LITERAL() { return GetToken(PlayscriptContentParser.BOOLEAN_LITERAL, 0); }
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 18, RULE_argument);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 1824L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,18,109,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,1,0,1,0,1,0,1,0,5,0,25,8,0,10,0,12,0,28,9,0,1,0,1,
		0,1,1,1,1,1,1,5,1,35,8,1,10,1,12,1,38,9,1,1,1,1,1,1,2,1,2,1,2,5,2,45,8,
		2,10,2,12,2,48,9,2,1,3,1,3,1,3,5,3,53,8,3,10,3,12,3,56,9,3,1,4,1,4,4,4,
		60,8,4,11,4,12,4,61,1,5,1,5,1,5,5,5,67,8,5,10,5,12,5,70,9,5,1,6,1,6,1,
		6,4,6,75,8,6,11,6,12,6,76,1,7,5,7,80,8,7,10,7,12,7,83,9,7,1,7,1,7,5,7,
		87,8,7,10,7,12,7,90,9,7,1,8,1,8,1,8,1,8,1,8,1,8,5,8,98,8,8,10,8,12,8,101,
		9,8,3,8,103,8,8,1,8,1,8,1,9,1,9,1,9,0,0,10,0,2,4,6,8,10,12,14,16,18,0,
		2,1,0,11,12,2,0,5,5,8,10,112,0,20,1,0,0,0,2,31,1,0,0,0,4,41,1,0,0,0,6,
		49,1,0,0,0,8,59,1,0,0,0,10,63,1,0,0,0,12,74,1,0,0,0,14,81,1,0,0,0,16,91,
		1,0,0,0,18,106,1,0,0,0,20,26,3,4,2,0,21,22,3,14,7,0,22,23,3,4,2,0,23,25,
		1,0,0,0,24,21,1,0,0,0,25,28,1,0,0,0,26,24,1,0,0,0,26,27,1,0,0,0,27,29,
		1,0,0,0,28,26,1,0,0,0,29,30,5,0,0,1,30,1,1,0,0,0,31,36,3,10,5,0,32,33,
		5,11,0,0,33,35,3,10,5,0,34,32,1,0,0,0,35,38,1,0,0,0,36,34,1,0,0,0,36,37,
		1,0,0,0,37,39,1,0,0,0,38,36,1,0,0,0,39,40,5,0,0,1,40,3,1,0,0,0,41,46,3,
		6,3,0,42,43,5,11,0,0,43,45,3,6,3,0,44,42,1,0,0,0,45,48,1,0,0,0,46,44,1,
		0,0,0,46,47,1,0,0,0,47,5,1,0,0,0,48,46,1,0,0,0,49,54,3,8,4,0,50,51,5,12,
		0,0,51,53,3,8,4,0,52,50,1,0,0,0,53,56,1,0,0,0,54,52,1,0,0,0,54,55,1,0,
		0,0,55,7,1,0,0,0,56,54,1,0,0,0,57,60,5,14,0,0,58,60,3,16,8,0,59,57,1,0,
		0,0,59,58,1,0,0,0,60,61,1,0,0,0,61,59,1,0,0,0,61,62,1,0,0,0,62,9,1,0,0,
		0,63,68,3,12,6,0,64,65,5,12,0,0,65,67,3,12,6,0,66,64,1,0,0,0,67,70,1,0,
		0,0,68,66,1,0,0,0,68,69,1,0,0,0,69,11,1,0,0,0,70,68,1,0,0,0,71,75,5,14,
		0,0,72,75,5,13,0,0,73,75,3,16,8,0,74,71,1,0,0,0,74,72,1,0,0,0,74,73,1,
		0,0,0,75,76,1,0,0,0,76,74,1,0,0,0,76,77,1,0,0,0,77,13,1,0,0,0,78,80,7,
		0,0,0,79,78,1,0,0,0,80,83,1,0,0,0,81,79,1,0,0,0,81,82,1,0,0,0,82,84,1,
		0,0,0,83,81,1,0,0,0,84,88,5,13,0,0,85,87,7,0,0,0,86,85,1,0,0,0,87,90,1,
		0,0,0,88,86,1,0,0,0,88,89,1,0,0,0,89,15,1,0,0,0,90,88,1,0,0,0,91,92,5,
		1,0,0,92,93,5,6,0,0,93,102,5,3,0,0,94,99,3,18,9,0,95,96,5,7,0,0,96,98,
		3,18,9,0,97,95,1,0,0,0,98,101,1,0,0,0,99,97,1,0,0,0,99,100,1,0,0,0,100,
		103,1,0,0,0,101,99,1,0,0,0,102,94,1,0,0,0,102,103,1,0,0,0,103,104,1,0,
		0,0,104,105,5,4,0,0,105,17,1,0,0,0,106,107,7,1,0,0,107,19,1,0,0,0,13,26,
		36,46,54,59,61,68,74,76,81,88,99,102
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
