//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Myriad-s-Projects/EasyPlayscript/EasyPlayscript.Core/core/playscript/definition/PlayscriptContentParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class PlayscriptContentParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		AT=1, COMMENT=2, LPAREN=3, RPAREN=4, STRING_LITERAL=5, IDENTIFIER=6, COMMA=7, 
		INTEGER_LITERAL=8, FLOAT_LITERAL=9, BOOLEAN_LITERAL=10, PLUS=11, DOT=12, 
		BLANK_LINE=13, SINGLE_NEWLINE=14, SLASH=15, TEXT=16, C_WS=17, S_PLUS=18, 
		C_LPAREN=19, C_RPAREN=20, C_DOT=21, C_COMMA=22;
	public const int
		RULE_scriptContent = 0, RULE_textContent = 1, RULE_page = 2, RULE_paragraph = 3, 
		RULE_line = 4, RULE_segment = 5, RULE_textParagraph = 6, RULE_textLine = 7, 
		RULE_pageBreak = 8, RULE_consumerCall = 9, RULE_qualifiedName = 10, RULE_argument = 11;
	public static readonly string[] ruleNames = {
		"scriptContent", "textContent", "page", "paragraph", "line", "segment", 
		"textParagraph", "textLine", "pageBreak", "consumerCall", "qualifiedName", 
		"argument"
	};

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "'/'", null, null, "'+'", "'('", "')'", "'.'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "AT", "COMMENT", "LPAREN", "RPAREN", "STRING_LITERAL", "IDENTIFIER", 
		"COMMA", "INTEGER_LITERAL", "FLOAT_LITERAL", "BOOLEAN_LITERAL", "PLUS", 
		"DOT", "BLANK_LINE", "SINGLE_NEWLINE", "SLASH", "TEXT", "C_WS", "S_PLUS", 
		"C_LPAREN", "C_RPAREN", "C_DOT", "C_COMMA"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlayscriptContentParser.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlayscriptContentParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public PlayscriptContentParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public PlayscriptContentParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class ScriptContentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public PageContext[] page() {
			return GetRuleContexts<PageContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PageContext page(int i) {
			return GetRuleContext<PageContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(PlayscriptContentParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public PageBreakContext[] pageBreak() {
			return GetRuleContexts<PageBreakContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public PageBreakContext pageBreak(int i) {
			return GetRuleContext<PageBreakContext>(i);
		}
		public ScriptContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_scriptContent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitScriptContent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ScriptContentContext scriptContent() {
		ScriptContentContext _localctx = new ScriptContentContext(Context, State);
		EnterRule(_localctx, 0, RULE_scriptContent);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 24;
			page();
			State = 30;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & 57344L) != 0)) {
				{
				{
				State = 25;
				pageBreak();
				State = 26;
				page();
				}
				}
				State = 32;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 33;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextContentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextParagraphContext[] textParagraph() {
			return GetRuleContexts<TextParagraphContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TextParagraphContext textParagraph(int i) {
			return GetRuleContext<TextParagraphContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(PlayscriptContentParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] BLANK_LINE() { return GetTokens(PlayscriptContentParser.BLANK_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLANK_LINE(int i) {
			return GetToken(PlayscriptContentParser.BLANK_LINE, i);
		}
		public TextContentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textContent; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextContent(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextContentContext textContent() {
		TextContentContext _localctx = new TextContentContext(Context, State);
		EnterRule(_localctx, 2, RULE_textContent);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 35;
			textParagraph();
			State = 40;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==BLANK_LINE) {
				{
				{
				State = 36;
				Match(BLANK_LINE);
				State = 37;
				textParagraph();
				}
				}
				State = 42;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 43;
			Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PageContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ParagraphContext[] paragraph() {
			return GetRuleContexts<ParagraphContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ParagraphContext paragraph(int i) {
			return GetRuleContext<ParagraphContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] BLANK_LINE() { return GetTokens(PlayscriptContentParser.BLANK_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLANK_LINE(int i) {
			return GetToken(PlayscriptContentParser.BLANK_LINE, i);
		}
		public PageContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_page; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPage(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PageContext page() {
		PageContext _localctx = new PageContext(Context, State);
		EnterRule(_localctx, 4, RULE_page);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 45;
			paragraph();
			State = 50;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 46;
					Match(BLANK_LINE);
					State = 47;
					paragraph();
					}
					} 
				}
				State = 52;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,2,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParagraphContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public LineContext[] line() {
			return GetRuleContexts<LineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public LineContext line(int i) {
			return GetRuleContext<LineContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SINGLE_NEWLINE() { return GetTokens(PlayscriptContentParser.SINGLE_NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_NEWLINE(int i) {
			return GetToken(PlayscriptContentParser.SINGLE_NEWLINE, i);
		}
		public ParagraphContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_paragraph; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParagraph(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParagraphContext paragraph() {
		ParagraphContext _localctx = new ParagraphContext(Context, State);
		EnterRule(_localctx, 6, RULE_paragraph);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 53;
			line();
			State = 58;
			ErrorHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER ) {
				if ( _alt==1 ) {
					{
					{
					State = 54;
					Match(SINGLE_NEWLINE);
					State = 55;
					line();
					}
					} 
				}
				State = 60;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,3,Context);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class LineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public SegmentContext[] segment() {
			return GetRuleContexts<SegmentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public SegmentContext segment(int i) {
			return GetRuleContext<SegmentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] PLUS() { return GetTokens(PlayscriptContentParser.PLUS); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode PLUS(int i) {
			return GetToken(PlayscriptContentParser.PLUS, i);
		}
		public LineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_line; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitLine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public LineContext line() {
		LineContext _localctx = new LineContext(Context, State);
		EnterRule(_localctx, 8, RULE_line);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 61;
			segment();
			State = 66;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==PLUS) {
				{
				{
				State = 62;
				Match(PLUS);
				State = 63;
				segment();
				}
				}
				State = 68;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SegmentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] TEXT() { return GetTokens(PlayscriptContentParser.TEXT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TEXT(int i) {
			return GetToken(PlayscriptContentParser.TEXT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConsumerCallContext[] consumerCall() {
			return GetRuleContexts<ConsumerCallContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConsumerCallContext consumerCall(int i) {
			return GetRuleContext<ConsumerCallContext>(i);
		}
		public SegmentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_segment; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSegment(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SegmentContext segment() {
		SegmentContext _localctx = new SegmentContext(Context, State);
		EnterRule(_localctx, 10, RULE_segment);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 71;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 71;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case TEXT:
					{
					State = 69;
					Match(TEXT);
					}
					break;
				case AT:
					{
					State = 70;
					consumerCall();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 73;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( _la==AT || _la==TEXT );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextParagraphContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public TextLineContext[] textLine() {
			return GetRuleContexts<TextLineContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public TextLineContext textLine(int i) {
			return GetRuleContext<TextLineContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SINGLE_NEWLINE() { return GetTokens(PlayscriptContentParser.SINGLE_NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_NEWLINE(int i) {
			return GetToken(PlayscriptContentParser.SINGLE_NEWLINE, i);
		}
		public TextParagraphContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textParagraph; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextParagraph(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextParagraphContext textParagraph() {
		TextParagraphContext _localctx = new TextParagraphContext(Context, State);
		EnterRule(_localctx, 12, RULE_textParagraph);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 75;
			textLine();
			State = 80;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==SINGLE_NEWLINE) {
				{
				{
				State = 76;
				Match(SINGLE_NEWLINE);
				State = 77;
				textLine();
				}
				}
				State = 82;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TextLineContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] TEXT() { return GetTokens(PlayscriptContentParser.TEXT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode TEXT(int i) {
			return GetToken(PlayscriptContentParser.TEXT, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SLASH() { return GetTokens(PlayscriptContentParser.SLASH); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH(int i) {
			return GetToken(PlayscriptContentParser.SLASH, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConsumerCallContext[] consumerCall() {
			return GetRuleContexts<ConsumerCallContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConsumerCallContext consumerCall(int i) {
			return GetRuleContext<ConsumerCallContext>(i);
		}
		public TextLineContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_textLine; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTextLine(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TextLineContext textLine() {
		TextLineContext _localctx = new TextLineContext(Context, State);
		EnterRule(_localctx, 14, RULE_textLine);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			do {
				{
				State = 86;
				ErrorHandler.Sync(this);
				switch (TokenStream.LA(1)) {
				case TEXT:
					{
					State = 83;
					Match(TEXT);
					}
					break;
				case SLASH:
					{
					State = 84;
					Match(SLASH);
					}
					break;
				case AT:
					{
					State = 85;
					consumerCall();
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 88;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			} while ( (((_la) & ~0x3f) == 0 && ((1L << _la) & 98306L) != 0) );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PageBreakContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SLASH() { return GetToken(PlayscriptContentParser.SLASH, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] SINGLE_NEWLINE() { return GetTokens(PlayscriptContentParser.SINGLE_NEWLINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SINGLE_NEWLINE(int i) {
			return GetToken(PlayscriptContentParser.SINGLE_NEWLINE, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] BLANK_LINE() { return GetTokens(PlayscriptContentParser.BLANK_LINE); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BLANK_LINE(int i) {
			return GetToken(PlayscriptContentParser.BLANK_LINE, i);
		}
		public PageBreakContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_pageBreak; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPageBreak(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PageBreakContext pageBreak() {
		PageBreakContext _localctx = new PageBreakContext(Context, State);
		EnterRule(_localctx, 16, RULE_pageBreak);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==BLANK_LINE || _la==SINGLE_NEWLINE) {
				{
				{
				State = 90;
				_la = TokenStream.LA(1);
				if ( !(_la==BLANK_LINE || _la==SINGLE_NEWLINE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 95;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			State = 96;
			Match(SLASH);
			State = 100;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==BLANK_LINE || _la==SINGLE_NEWLINE) {
				{
				{
				State = 97;
				_la = TokenStream.LA(1);
				if ( !(_la==BLANK_LINE || _la==SINGLE_NEWLINE) ) {
				ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				}
				State = 102;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConsumerCallContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AT() { return GetToken(PlayscriptContentParser.AT, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public QualifiedNameContext qualifiedName() {
			return GetRuleContext<QualifiedNameContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode LPAREN() { return GetToken(PlayscriptContentParser.LPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode RPAREN() { return GetToken(PlayscriptContentParser.RPAREN, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext[] argument() {
			return GetRuleContexts<ArgumentContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public ArgumentContext argument(int i) {
			return GetRuleContext<ArgumentContext>(i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] COMMA() { return GetTokens(PlayscriptContentParser.COMMA); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode COMMA(int i) {
			return GetToken(PlayscriptContentParser.COMMA, i);
		}
		public ConsumerCallContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_consumerCall; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConsumerCall(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConsumerCallContext consumerCall() {
		ConsumerCallContext _localctx = new ConsumerCallContext(Context, State);
		EnterRule(_localctx, 18, RULE_consumerCall);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 103;
			Match(AT);
			State = 104;
			qualifiedName();
			State = 105;
			Match(LPAREN);
			State = 114;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			if ((((_la) & ~0x3f) == 0 && ((1L << _la) & 1824L) != 0)) {
				{
				State = 106;
				argument();
				State = 111;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
				while (_la==COMMA) {
					{
					{
					State = 107;
					Match(COMMA);
					State = 108;
					argument();
					}
					}
					State = 113;
					ErrorHandler.Sync(this);
					_la = TokenStream.LA(1);
				}
				}
			}

			State = 116;
			Match(RPAREN);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class QualifiedNameContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] IDENTIFIER() { return GetTokens(PlayscriptContentParser.IDENTIFIER); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode IDENTIFIER(int i) {
			return GetToken(PlayscriptContentParser.IDENTIFIER, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DOT() { return GetTokens(PlayscriptContentParser.DOT); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DOT(int i) {
			return GetToken(PlayscriptContentParser.DOT, i);
		}
		public QualifiedNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_qualifiedName; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitQualifiedName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public QualifiedNameContext qualifiedName() {
		QualifiedNameContext _localctx = new QualifiedNameContext(Context, State);
		EnterRule(_localctx, 20, RULE_qualifiedName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 118;
			Match(IDENTIFIER);
			State = 123;
			ErrorHandler.Sync(this);
			_la = TokenStream.LA(1);
			while (_la==DOT) {
				{
				{
				State = 119;
				Match(DOT);
				State = 120;
				Match(IDENTIFIER);
				}
				}
				State = 125;
				ErrorHandler.Sync(this);
				_la = TokenStream.LA(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArgumentContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode STRING_LITERAL() { return GetToken(PlayscriptContentParser.STRING_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode INTEGER_LITERAL() { return GetToken(PlayscriptContentParser.INTEGER_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode FLOAT_LITERAL() { return GetToken(PlayscriptContentParser.FLOAT_LITERAL, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode BOOLEAN_LITERAL() { return GetToken(PlayscriptContentParser.BOOLEAN_LITERAL, 0); }
		public ArgumentContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_argument; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IPlayscriptContentParserVisitor<TResult> typedVisitor = visitor as IPlayscriptContentParserVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArgument(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArgumentContext argument() {
		ArgumentContext _localctx = new ArgumentContext(Context, State);
		EnterRule(_localctx, 22, RULE_argument);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			_la = TokenStream.LA(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 1824L) != 0)) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,22,129,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,1,0,1,0,1,0,1,0,5,0,29,8,0,10,
		0,12,0,32,9,0,1,0,1,0,1,1,1,1,1,1,5,1,39,8,1,10,1,12,1,42,9,1,1,1,1,1,
		1,2,1,2,1,2,5,2,49,8,2,10,2,12,2,52,9,2,1,3,1,3,1,3,5,3,57,8,3,10,3,12,
		3,60,9,3,1,4,1,4,1,4,5,4,65,8,4,10,4,12,4,68,9,4,1,5,1,5,4,5,72,8,5,11,
		5,12,5,73,1,6,1,6,1,6,5,6,79,8,6,10,6,12,6,82,9,6,1,7,1,7,1,7,4,7,87,8,
		7,11,7,12,7,88,1,8,5,8,92,8,8,10,8,12,8,95,9,8,1,8,1,8,5,8,99,8,8,10,8,
		12,8,102,9,8,1,9,1,9,1,9,1,9,1,9,1,9,5,9,110,8,9,10,9,12,9,113,9,9,3,9,
		115,8,9,1,9,1,9,1,10,1,10,1,10,5,10,122,8,10,10,10,12,10,125,9,10,1,11,
		1,11,1,11,0,0,12,0,2,4,6,8,10,12,14,16,18,20,22,0,2,1,0,13,14,2,0,5,5,
		8,10,132,0,24,1,0,0,0,2,35,1,0,0,0,4,45,1,0,0,0,6,53,1,0,0,0,8,61,1,0,
		0,0,10,71,1,0,0,0,12,75,1,0,0,0,14,86,1,0,0,0,16,93,1,0,0,0,18,103,1,0,
		0,0,20,118,1,0,0,0,22,126,1,0,0,0,24,30,3,4,2,0,25,26,3,16,8,0,26,27,3,
		4,2,0,27,29,1,0,0,0,28,25,1,0,0,0,29,32,1,0,0,0,30,28,1,0,0,0,30,31,1,
		0,0,0,31,33,1,0,0,0,32,30,1,0,0,0,33,34,5,0,0,1,34,1,1,0,0,0,35,40,3,12,
		6,0,36,37,5,13,0,0,37,39,3,12,6,0,38,36,1,0,0,0,39,42,1,0,0,0,40,38,1,
		0,0,0,40,41,1,0,0,0,41,43,1,0,0,0,42,40,1,0,0,0,43,44,5,0,0,1,44,3,1,0,
		0,0,45,50,3,6,3,0,46,47,5,13,0,0,47,49,3,6,3,0,48,46,1,0,0,0,49,52,1,0,
		0,0,50,48,1,0,0,0,50,51,1,0,0,0,51,5,1,0,0,0,52,50,1,0,0,0,53,58,3,8,4,
		0,54,55,5,14,0,0,55,57,3,8,4,0,56,54,1,0,0,0,57,60,1,0,0,0,58,56,1,0,0,
		0,58,59,1,0,0,0,59,7,1,0,0,0,60,58,1,0,0,0,61,66,3,10,5,0,62,63,5,11,0,
		0,63,65,3,10,5,0,64,62,1,0,0,0,65,68,1,0,0,0,66,64,1,0,0,0,66,67,1,0,0,
		0,67,9,1,0,0,0,68,66,1,0,0,0,69,72,5,16,0,0,70,72,3,18,9,0,71,69,1,0,0,
		0,71,70,1,0,0,0,72,73,1,0,0,0,73,71,1,0,0,0,73,74,1,0,0,0,74,11,1,0,0,
		0,75,80,3,14,7,0,76,77,5,14,0,0,77,79,3,14,7,0,78,76,1,0,0,0,79,82,1,0,
		0,0,80,78,1,0,0,0,80,81,1,0,0,0,81,13,1,0,0,0,82,80,1,0,0,0,83,87,5,16,
		0,0,84,87,5,15,0,0,85,87,3,18,9,0,86,83,1,0,0,0,86,84,1,0,0,0,86,85,1,
		0,0,0,87,88,1,0,0,0,88,86,1,0,0,0,88,89,1,0,0,0,89,15,1,0,0,0,90,92,7,
		0,0,0,91,90,1,0,0,0,92,95,1,0,0,0,93,91,1,0,0,0,93,94,1,0,0,0,94,96,1,
		0,0,0,95,93,1,0,0,0,96,100,5,15,0,0,97,99,7,0,0,0,98,97,1,0,0,0,99,102,
		1,0,0,0,100,98,1,0,0,0,100,101,1,0,0,0,101,17,1,0,0,0,102,100,1,0,0,0,
		103,104,5,1,0,0,104,105,3,20,10,0,105,114,5,3,0,0,106,111,3,22,11,0,107,
		108,5,7,0,0,108,110,3,22,11,0,109,107,1,0,0,0,110,113,1,0,0,0,111,109,
		1,0,0,0,111,112,1,0,0,0,112,115,1,0,0,0,113,111,1,0,0,0,114,106,1,0,0,
		0,114,115,1,0,0,0,115,116,1,0,0,0,116,117,5,4,0,0,117,19,1,0,0,0,118,123,
		5,6,0,0,119,120,5,12,0,0,120,122,5,6,0,0,121,119,1,0,0,0,122,125,1,0,0,
		0,123,121,1,0,0,0,123,124,1,0,0,0,124,21,1,0,0,0,125,123,1,0,0,0,126,127,
		7,1,0,0,127,23,1,0,0,0,15,30,40,50,58,66,71,73,80,86,88,93,100,111,114,
		123
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
