//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyPlayscript/EasyPlayscript/core/playscript/definition/PlayscriptContentLexer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class PlayscriptContentLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		AT=1, COMMENT=2, LPAREN=3, RPAREN=4, STRING_LITERAL=5, IDENTIFIER=6, BLANK_LINE=7, 
		SINGLE_NEWLINE=8, SLASH=9, TEXT=10, C_WS=11, C_LPAREN=12, C_RPAREN=13;
	public const int
		IN_CALL=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "IN_CALL"
	};

	public static readonly string[] ruleNames = {
		"S_AT", "S_COMMENT", "BLANK_LINE", "SINGLE_NEWLINE", "SLASH", "TEXT", 
		"C_LPAREN", "C_RPAREN", "C_STRING_LITERAL", "C_IDENTIFIER", "C_WS"
	};


	public PlayscriptContentLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PlayscriptContentLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, "'/'", null, null, 
		"'('", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "AT", "COMMENT", "LPAREN", "RPAREN", "STRING_LITERAL", "IDENTIFIER", 
		"BLANK_LINE", "SINGLE_NEWLINE", "SLASH", "TEXT", "C_WS", "C_LPAREN", "C_RPAREN"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlayscriptContentLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlayscriptContentLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,13,104,6,-1,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,
		6,7,6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,1,0,1,0,1,0,1,0,1,0,1,1,1,1,5,
		1,32,8,1,10,1,12,1,35,9,1,1,1,1,1,1,1,1,2,3,2,41,8,2,1,2,1,2,5,2,45,8,
		2,10,2,12,2,48,9,2,1,2,3,2,51,8,2,1,2,1,2,1,3,3,3,56,8,3,1,3,1,3,1,4,1,
		4,1,5,4,5,63,8,5,11,5,12,5,64,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,8,
		1,8,1,8,1,8,5,8,80,8,8,10,8,12,8,83,9,8,1,8,1,8,1,8,1,8,1,9,1,9,5,9,91,
		8,9,10,9,12,9,94,9,9,1,9,1,9,1,10,4,10,99,8,10,11,10,12,10,100,1,10,1,
		10,0,0,11,2,0,4,0,6,7,8,8,10,9,12,10,14,12,16,13,18,0,20,0,22,11,2,0,1,
		6,2,0,10,10,13,13,2,0,9,9,32,32,6,0,10,10,13,13,35,35,47,47,64,64,93,93,
		4,0,10,10,13,13,34,34,92,92,3,0,65,90,95,95,97,122,4,0,48,57,65,90,95,
		95,97,122,112,0,2,1,0,0,0,0,4,1,0,0,0,0,6,1,0,0,0,0,8,1,0,0,0,0,10,1,0,
		0,0,0,12,1,0,0,0,1,14,1,0,0,0,1,16,1,0,0,0,1,18,1,0,0,0,1,20,1,0,0,0,1,
		22,1,0,0,0,2,24,1,0,0,0,4,29,1,0,0,0,6,40,1,0,0,0,8,55,1,0,0,0,10,59,1,
		0,0,0,12,62,1,0,0,0,14,66,1,0,0,0,16,70,1,0,0,0,18,75,1,0,0,0,20,88,1,
		0,0,0,22,98,1,0,0,0,24,25,5,64,0,0,25,26,1,0,0,0,26,27,6,0,0,0,27,28,6,
		0,1,0,28,3,1,0,0,0,29,33,5,35,0,0,30,32,8,0,0,0,31,30,1,0,0,0,32,35,1,
		0,0,0,33,31,1,0,0,0,33,34,1,0,0,0,34,36,1,0,0,0,35,33,1,0,0,0,36,37,6,
		1,2,0,37,38,6,1,3,0,38,5,1,0,0,0,39,41,5,13,0,0,40,39,1,0,0,0,40,41,1,
		0,0,0,41,42,1,0,0,0,42,46,5,10,0,0,43,45,7,1,0,0,44,43,1,0,0,0,45,48,1,
		0,0,0,46,44,1,0,0,0,46,47,1,0,0,0,47,50,1,0,0,0,48,46,1,0,0,0,49,51,5,
		13,0,0,50,49,1,0,0,0,50,51,1,0,0,0,51,52,1,0,0,0,52,53,5,10,0,0,53,7,1,
		0,0,0,54,56,5,13,0,0,55,54,1,0,0,0,55,56,1,0,0,0,56,57,1,0,0,0,57,58,5,
		10,0,0,58,9,1,0,0,0,59,60,5,47,0,0,60,11,1,0,0,0,61,63,8,2,0,0,62,61,1,
		0,0,0,63,64,1,0,0,0,64,62,1,0,0,0,64,65,1,0,0,0,65,13,1,0,0,0,66,67,5,
		40,0,0,67,68,1,0,0,0,68,69,6,6,4,0,69,15,1,0,0,0,70,71,5,41,0,0,71,72,
		1,0,0,0,72,73,6,7,5,0,73,74,6,7,6,0,74,17,1,0,0,0,75,81,5,34,0,0,76,80,
		8,3,0,0,77,78,5,92,0,0,78,80,9,0,0,0,79,76,1,0,0,0,79,77,1,0,0,0,80,83,
		1,0,0,0,81,79,1,0,0,0,81,82,1,0,0,0,82,84,1,0,0,0,83,81,1,0,0,0,84,85,
		5,34,0,0,85,86,1,0,0,0,86,87,6,8,7,0,87,19,1,0,0,0,88,92,7,4,0,0,89,91,
		7,5,0,0,90,89,1,0,0,0,91,94,1,0,0,0,92,90,1,0,0,0,92,93,1,0,0,0,93,95,
		1,0,0,0,94,92,1,0,0,0,95,96,6,9,8,0,96,21,1,0,0,0,97,99,7,1,0,0,98,97,
		1,0,0,0,99,100,1,0,0,0,100,98,1,0,0,0,100,101,1,0,0,0,101,102,1,0,0,0,
		102,103,6,10,9,0,103,23,1,0,0,0,12,0,1,33,40,46,50,55,64,79,81,92,100,
		10,7,1,0,5,1,0,7,2,0,0,1,0,7,3,0,7,4,0,4,0,0,7,5,0,7,6,0,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
