//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyPlayscript/EasyPlayscript.Core/core/playscript/definition/PlayscriptContentParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PlayscriptContentParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPlayscriptContentParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptContentParser.scriptContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScriptContent([NotNull] PlayscriptContentParser.ScriptContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptContentParser.page"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPage([NotNull] PlayscriptContentParser.PageContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptContentParser.paragraph"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParagraph([NotNull] PlayscriptContentParser.ParagraphContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptContentParser.line"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLine([NotNull] PlayscriptContentParser.LineContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptContentParser.pageBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPageBreak([NotNull] PlayscriptContentParser.PageBreakContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptContentParser.consumerCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConsumerCall([NotNull] PlayscriptContentParser.ConsumerCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptContentParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] PlayscriptContentParser.ArgumentContext context);
}
