//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyPlayscript/EasyPlayscript.Core/core/playscript/definition/PlayscriptContentLexer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class PlayscriptContentLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		AT=1, COMMENT=2, LPAREN=3, RPAREN=4, STRING_LITERAL=5, IDENTIFIER=6, COMMA=7, 
		INTEGER_LITERAL=8, FLOAT_LITERAL=9, BOOLEAN_LITERAL=10, BLANK_LINE=11, 
		SINGLE_NEWLINE=12, SLASH=13, TEXT=14, C_WS=15, C_LPAREN=16, C_RPAREN=17, 
		C_COMMA=18;
	public const int
		IN_CALL=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "IN_CALL"
	};

	public static readonly string[] ruleNames = {
		"S_AT", "S_COMMENT", "BLANK_LINE", "SINGLE_NEWLINE", "SLASH", "TEXT", 
		"C_LPAREN", "C_RPAREN", "C_STRING_LITERAL", "C_FLOAT_LITERAL", "C_INTEGER_LITERAL", 
		"C_BOOLEAN_LITERAL", "C_IDENTIFIER", "C_COMMA", "C_WS"
	};


	public PlayscriptContentLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PlayscriptContentLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, "'/'", null, null, "'('", "')'", "','"
	};
	private static readonly string[] _SymbolicNames = {
		null, "AT", "COMMENT", "LPAREN", "RPAREN", "STRING_LITERAL", "IDENTIFIER", 
		"COMMA", "INTEGER_LITERAL", "FLOAT_LITERAL", "BOOLEAN_LITERAL", "BLANK_LINE", 
		"SINGLE_NEWLINE", "SLASH", "TEXT", "C_WS", "C_LPAREN", "C_RPAREN", "C_COMMA"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlayscriptContentLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlayscriptContentLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,18,179,6,-1,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,
		6,7,6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,
		2,14,7,14,1,0,1,0,1,0,1,0,1,0,1,1,1,1,5,1,40,8,1,10,1,12,1,43,9,1,1,1,
		1,1,1,1,1,2,3,2,49,8,2,1,2,1,2,5,2,53,8,2,10,2,12,2,56,9,2,1,2,3,2,59,
		8,2,1,2,1,2,1,3,3,3,64,8,3,1,3,1,3,1,4,1,4,1,5,1,5,1,5,4,5,73,8,5,11,5,
		12,5,74,1,6,1,6,1,6,1,6,1,7,1,7,1,7,1,7,1,7,1,8,1,8,1,8,1,8,5,8,90,8,8,
		10,8,12,8,93,9,8,1,8,1,8,1,8,1,8,1,9,3,9,100,8,9,1,9,4,9,103,8,9,11,9,
		12,9,104,1,9,1,9,4,9,109,8,9,11,9,12,9,110,1,9,1,9,3,9,115,8,9,1,9,4,9,
		118,8,9,11,9,12,9,119,3,9,122,8,9,1,9,1,9,3,9,126,8,9,1,9,4,9,129,8,9,
		11,9,12,9,130,3,9,133,8,9,1,9,1,9,1,10,3,10,138,8,10,1,10,4,10,141,8,10,
		11,10,12,10,142,1,10,1,10,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,11,
		3,11,156,8,11,1,11,1,11,1,12,1,12,5,12,162,8,12,10,12,12,12,165,9,12,1,
		12,1,12,1,13,1,13,1,13,1,13,1,14,4,14,174,8,14,11,14,12,14,175,1,14,1,
		14,0,0,15,2,0,4,0,6,11,8,12,10,13,12,14,14,16,16,17,18,0,20,0,22,0,24,
		0,26,0,28,18,30,15,2,0,1,8,2,0,10,10,13,13,2,0,9,9,32,32,6,0,10,10,13,
		13,35,35,47,47,64,64,92,92,4,0,10,10,13,13,34,34,92,92,1,0,48,57,2,0,69,
		69,101,101,3,0,65,90,95,95,97,122,4,0,48,57,65,90,95,95,97,122,200,0,2,
		1,0,0,0,0,4,1,0,0,0,0,6,1,0,0,0,0,8,1,0,0,0,0,10,1,0,0,0,0,12,1,0,0,0,
		1,14,1,0,0,0,1,16,1,0,0,0,1,18,1,0,0,0,1,20,1,0,0,0,1,22,1,0,0,0,1,24,
		1,0,0,0,1,26,1,0,0,0,1,28,1,0,0,0,1,30,1,0,0,0,2,32,1,0,0,0,4,37,1,0,0,
		0,6,48,1,0,0,0,8,63,1,0,0,0,10,67,1,0,0,0,12,72,1,0,0,0,14,76,1,0,0,0,
		16,80,1,0,0,0,18,85,1,0,0,0,20,99,1,0,0,0,22,137,1,0,0,0,24,155,1,0,0,
		0,26,159,1,0,0,0,28,168,1,0,0,0,30,173,1,0,0,0,32,33,5,64,0,0,33,34,1,
		0,0,0,34,35,6,0,0,0,35,36,6,0,1,0,36,3,1,0,0,0,37,41,5,35,0,0,38,40,8,
		0,0,0,39,38,1,0,0,0,40,43,1,0,0,0,41,39,1,0,0,0,41,42,1,0,0,0,42,44,1,
		0,0,0,43,41,1,0,0,0,44,45,6,1,2,0,45,46,6,1,3,0,46,5,1,0,0,0,47,49,5,13,
		0,0,48,47,1,0,0,0,48,49,1,0,0,0,49,50,1,0,0,0,50,54,5,10,0,0,51,53,7,1,
		0,0,52,51,1,0,0,0,53,56,1,0,0,0,54,52,1,0,0,0,54,55,1,0,0,0,55,58,1,0,
		0,0,56,54,1,0,0,0,57,59,5,13,0,0,58,57,1,0,0,0,58,59,1,0,0,0,59,60,1,0,
		0,0,60,61,5,10,0,0,61,7,1,0,0,0,62,64,5,13,0,0,63,62,1,0,0,0,63,64,1,0,
		0,0,64,65,1,0,0,0,65,66,5,10,0,0,66,9,1,0,0,0,67,68,5,47,0,0,68,11,1,0,
		0,0,69,70,5,92,0,0,70,73,8,0,0,0,71,73,8,2,0,0,72,69,1,0,0,0,72,71,1,0,
		0,0,73,74,1,0,0,0,74,72,1,0,0,0,74,75,1,0,0,0,75,13,1,0,0,0,76,77,5,40,
		0,0,77,78,1,0,0,0,78,79,6,6,4,0,79,15,1,0,0,0,80,81,5,41,0,0,81,82,1,0,
		0,0,82,83,6,7,5,0,83,84,6,7,6,0,84,17,1,0,0,0,85,91,5,34,0,0,86,90,8,3,
		0,0,87,88,5,92,0,0,88,90,9,0,0,0,89,86,1,0,0,0,89,87,1,0,0,0,90,93,1,0,
		0,0,91,89,1,0,0,0,91,92,1,0,0,0,92,94,1,0,0,0,93,91,1,0,0,0,94,95,5,34,
		0,0,95,96,1,0,0,0,96,97,6,8,7,0,97,19,1,0,0,0,98,100,5,45,0,0,99,98,1,
		0,0,0,99,100,1,0,0,0,100,102,1,0,0,0,101,103,7,4,0,0,102,101,1,0,0,0,103,
		104,1,0,0,0,104,102,1,0,0,0,104,105,1,0,0,0,105,132,1,0,0,0,106,108,5,
		46,0,0,107,109,7,4,0,0,108,107,1,0,0,0,109,110,1,0,0,0,110,108,1,0,0,0,
		110,111,1,0,0,0,111,121,1,0,0,0,112,114,7,5,0,0,113,115,5,45,0,0,114,113,
		1,0,0,0,114,115,1,0,0,0,115,117,1,0,0,0,116,118,7,4,0,0,117,116,1,0,0,
		0,118,119,1,0,0,0,119,117,1,0,0,0,119,120,1,0,0,0,120,122,1,0,0,0,121,
		112,1,0,0,0,121,122,1,0,0,0,122,133,1,0,0,0,123,125,7,5,0,0,124,126,5,
		45,0,0,125,124,1,0,0,0,125,126,1,0,0,0,126,128,1,0,0,0,127,129,7,4,0,0,
		128,127,1,0,0,0,129,130,1,0,0,0,130,128,1,0,0,0,130,131,1,0,0,0,131,133,
		1,0,0,0,132,106,1,0,0,0,132,123,1,0,0,0,133,134,1,0,0,0,134,135,6,9,8,
		0,135,21,1,0,0,0,136,138,5,45,0,0,137,136,1,0,0,0,137,138,1,0,0,0,138,
		140,1,0,0,0,139,141,7,4,0,0,140,139,1,0,0,0,141,142,1,0,0,0,142,140,1,
		0,0,0,142,143,1,0,0,0,143,144,1,0,0,0,144,145,6,10,9,0,145,23,1,0,0,0,
		146,147,5,116,0,0,147,148,5,114,0,0,148,149,5,117,0,0,149,156,5,101,0,
		0,150,151,5,102,0,0,151,152,5,97,0,0,152,153,5,108,0,0,153,154,5,115,0,
		0,154,156,5,101,0,0,155,146,1,0,0,0,155,150,1,0,0,0,156,157,1,0,0,0,157,
		158,6,11,10,0,158,25,1,0,0,0,159,163,7,6,0,0,160,162,7,7,0,0,161,160,1,
		0,0,0,162,165,1,0,0,0,163,161,1,0,0,0,163,164,1,0,0,0,164,166,1,0,0,0,
		165,163,1,0,0,0,166,167,6,12,11,0,167,27,1,0,0,0,168,169,5,44,0,0,169,
		170,1,0,0,0,170,171,6,13,12,0,171,29,1,0,0,0,172,174,7,1,0,0,173,172,1,
		0,0,0,174,175,1,0,0,0,175,173,1,0,0,0,175,176,1,0,0,0,176,177,1,0,0,0,
		177,178,6,14,13,0,178,31,1,0,0,0,25,0,1,41,48,54,58,63,72,74,89,91,99,
		104,110,114,119,121,125,130,132,137,142,155,163,175,14,7,1,0,5,1,0,7,2,
		0,0,1,0,7,3,0,7,4,0,4,0,0,7,5,0,7,9,0,7,8,0,7,10,0,7,6,0,7,7,0,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
