using System.CodeDom.Compiler;
using System.IO;
using System.Text;

namespace EasyPlayscript.Parsing;

public class PlayscriptCodeBuilder(string fileName) : PlayscriptParserBaseVisitor<string>
{
    public override string VisitPlayscript(PlayscriptParser.PlayscriptContext context)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("using EasyPlayscript;");
        indented.WriteLine("using EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine($"public static class {fileName}");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public static void Run(ScriptRegistry registry)");
        indented.WriteLine("{");
        indented.Indent++;

        foreach (var statement in context.statement())
        {
            var code = Visit(statement);
            if (!string.IsNullOrEmpty(code))
            {
                indented.Write(code);
            }
        }

        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    public override string VisitStatement(PlayscriptParser.StatementContext context)
    {
        if (context.scriptBlock() != null)
            return Visit(context.scriptBlock());
        if (context.externalCall() != null)
            return Visit(context.externalCall());
        return string.Empty;
    }

    public override string VisitScriptBlock(PlayscriptParser.ScriptBlockContext context)
    {
        var externalCall = context.externalCall();
        var identifier = externalCall.IDENTIFIER().GetText();
        var arg = externalCall.STRING_LITERAL().GetText();
        var cleanArg = arg.Trim('"');

        var block = new ScriptBlock();

        foreach (var content in context.scriptContent())
        {
            if (content.sentence() != null)
            {
                var sentence = content.sentence();
                var parts = sentence.sentencePart();
                var sb = new StringBuilder();
                foreach (var part in parts)
                {
                    foreach (var text in part.TEXT())
                    {
                        sb.Append(text.GetText());
                    }
                }
                block.Content.Add(sb.ToString());
            }
            else if (content.internalCall() != null)
            {
                var callIdentifier = content.internalCall().IDENTIFIER().GetText();
                var callArg = content.internalCall().STRING_LITERAL().GetText();
                var cleanCallArg = callArg.Trim('"');
                block.Content.Add($"@{callIdentifier}(\"{cleanCallArg}\")");
            }
        }

        return identifier switch
        {
            "script" => PlayscriptHandlers.Script(cleanArg, block),
            "text" => PlayscriptHandlers.Text(cleanArg, block),
            _ => $"// TODO: @{identifier}(\"{cleanArg}\")\n"
        };
    }

    public override string VisitExternalCall(PlayscriptParser.ExternalCallContext context)
    {
        var identifier = context.IDENTIFIER().GetText();
        var arg = context.STRING_LITERAL().GetText();
        return $"// TODO: top-level external call @{identifier}({arg})\n";
    }
}
