//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyPlayscript/EasyPlayscript.Core/core/playscript/definition/PlayscriptStructureLexer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class PlayscriptStructureLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SCRIPT=1, TEXT=2, INTERFACE=3, LBRACKET=4, IDENTIFIER=5, WS=6, NEWLINE=7, 
		COMMENT=8, RAW_CONTENT=9, RBRACKET=10;
	public const int
		IN_RAW=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "IN_RAW"
	};

	public static readonly string[] ruleNames = {
		"SCRIPT", "TEXT", "INTERFACE", "LBRACKET", "IDENTIFIER", "WS", "NEWLINE", 
		"COMMENT", "RAW_CONTENT", "RBRACKET"
	};


	public PlayscriptStructureLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PlayscriptStructureLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'script'", "'text'", "'interface'", "'['", null, null, null, null, 
		null, "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SCRIPT", "TEXT", "INTERFACE", "LBRACKET", "IDENTIFIER", "WS", "NEWLINE", 
		"COMMENT", "RAW_CONTENT", "RBRACKET"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlayscriptStructureLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlayscriptStructureLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,10,87,6,-1,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,
		6,7,6,2,7,7,7,2,8,7,8,2,9,7,9,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,
		1,1,1,1,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,4,1,
		4,5,4,51,8,4,10,4,12,4,54,9,4,1,5,4,5,57,8,5,11,5,12,5,58,1,5,1,5,1,6,
		3,6,64,8,6,1,6,1,6,1,6,1,6,1,7,1,7,5,7,72,8,7,10,7,12,7,75,9,7,1,7,1,7,
		1,8,4,8,80,8,8,11,8,12,8,81,1,9,1,9,1,9,1,9,0,0,10,2,1,4,2,6,3,8,4,10,
		5,12,6,14,7,16,8,18,9,20,10,2,0,1,5,3,0,65,90,95,95,97,122,4,0,48,57,65,
		90,95,95,97,122,2,0,9,9,32,32,2,0,10,10,13,13,1,0,93,93,90,0,2,1,0,0,0,
		0,4,1,0,0,0,0,6,1,0,0,0,0,8,1,0,0,0,0,10,1,0,0,0,0,12,1,0,0,0,0,14,1,0,
		0,0,0,16,1,0,0,0,1,18,1,0,0,0,1,20,1,0,0,0,2,22,1,0,0,0,4,29,1,0,0,0,6,
		34,1,0,0,0,8,44,1,0,0,0,10,48,1,0,0,0,12,56,1,0,0,0,14,63,1,0,0,0,16,69,
		1,0,0,0,18,79,1,0,0,0,20,83,1,0,0,0,22,23,5,115,0,0,23,24,5,99,0,0,24,
		25,5,114,0,0,25,26,5,105,0,0,26,27,5,112,0,0,27,28,5,116,0,0,28,3,1,0,
		0,0,29,30,5,116,0,0,30,31,5,101,0,0,31,32,5,120,0,0,32,33,5,116,0,0,33,
		5,1,0,0,0,34,35,5,105,0,0,35,36,5,110,0,0,36,37,5,116,0,0,37,38,5,101,
		0,0,38,39,5,114,0,0,39,40,5,102,0,0,40,41,5,97,0,0,41,42,5,99,0,0,42,43,
		5,101,0,0,43,7,1,0,0,0,44,45,5,91,0,0,45,46,1,0,0,0,46,47,6,3,0,0,47,9,
		1,0,0,0,48,52,7,0,0,0,49,51,7,1,0,0,50,49,1,0,0,0,51,54,1,0,0,0,52,50,
		1,0,0,0,52,53,1,0,0,0,53,11,1,0,0,0,54,52,1,0,0,0,55,57,7,2,0,0,56,55,
		1,0,0,0,57,58,1,0,0,0,58,56,1,0,0,0,58,59,1,0,0,0,59,60,1,0,0,0,60,61,
		6,5,1,0,61,13,1,0,0,0,62,64,5,13,0,0,63,62,1,0,0,0,63,64,1,0,0,0,64,65,
		1,0,0,0,65,66,5,10,0,0,66,67,1,0,0,0,67,68,6,6,1,0,68,15,1,0,0,0,69,73,
		5,35,0,0,70,72,8,3,0,0,71,70,1,0,0,0,72,75,1,0,0,0,73,71,1,0,0,0,73,74,
		1,0,0,0,74,76,1,0,0,0,75,73,1,0,0,0,76,77,6,7,1,0,77,17,1,0,0,0,78,80,
		8,4,0,0,79,78,1,0,0,0,80,81,1,0,0,0,81,79,1,0,0,0,81,82,1,0,0,0,82,19,
		1,0,0,0,83,84,5,93,0,0,84,85,1,0,0,0,85,86,6,9,2,0,86,21,1,0,0,0,7,0,1,
		52,58,63,73,81,3,5,1,0,6,0,0,4,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
