//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/Myriad-s-Projects/EasyPlayscript/EasyPlayscript.Core/core/playscript/definition/PlayscriptStructureParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="PlayscriptStructureParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPlayscriptStructureParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlayscriptStructureParser.playscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlayscript([NotNull] PlayscriptStructureParser.PlayscriptContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlayscriptStructureParser.playscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlayscript([NotNull] PlayscriptStructureParser.PlayscriptContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlayscriptStructureParser.topLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTopLevelStatement([NotNull] PlayscriptStructureParser.TopLevelStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlayscriptStructureParser.topLevelStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTopLevelStatement([NotNull] PlayscriptStructureParser.TopLevelStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlayscriptStructureParser.blockType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockType([NotNull] PlayscriptStructureParser.BlockTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlayscriptStructureParser.blockType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockType([NotNull] PlayscriptStructureParser.BlockTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlayscriptStructureParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamList([NotNull] PlayscriptStructureParser.ParamListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlayscriptStructureParser.paramList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamList([NotNull] PlayscriptStructureParser.ParamListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlayscriptStructureParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameter([NotNull] PlayscriptStructureParser.ParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlayscriptStructureParser.parameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameter([NotNull] PlayscriptStructureParser.ParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="PlayscriptStructureParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTypeSpec([NotNull] PlayscriptStructureParser.TypeSpecContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="PlayscriptStructureParser.typeSpec"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTypeSpec([NotNull] PlayscriptStructureParser.TypeSpecContext context);
}
