//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from PlayscriptStructureLexer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class PlayscriptStructureLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		SCRIPT=1, TEXT=2, VARIATION=3, DEFAULT=4, ASYNC=5, INTERFACE=6, LBRACKET=7, 
		COLON=8, LPAREN=9, RPAREN=10, COMMA=11, STRING_TYPE=12, INT_TYPE=13, DECIMAL_TYPE=14, 
		BOOL_TYPE=15, VOID_TYPE=16, IDENTIFIER=17, WS=18, NEWLINE=19, COMMENT=20, 
		RAW_CONTENT=21, RBRACKET=22;
	public const int
		IN_RAW=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "IN_RAW"
	};

	public static readonly string[] ruleNames = {
		"SCRIPT", "TEXT", "VARIATION", "DEFAULT", "ASYNC", "INTERFACE", "LBRACKET", 
		"COLON", "LPAREN", "RPAREN", "COMMA", "STRING_TYPE", "INT_TYPE", "DECIMAL_TYPE", 
		"BOOL_TYPE", "VOID_TYPE", "IDENTIFIER", "WS", "NEWLINE", "COMMENT", "RAW_CONTENT", 
		"RBRACKET"
	};


	public PlayscriptStructureLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PlayscriptStructureLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'script'", "'text'", "'variation'", "'default'", "'async'", "'interface'", 
		"'['", "':'", "'('", "')'", "','", "'string'", "'int'", "'decimal'", "'bool'", 
		"'void'", null, null, null, null, null, "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "SCRIPT", "TEXT", "VARIATION", "DEFAULT", "ASYNC", "INTERFACE", 
		"LBRACKET", "COLON", "LPAREN", "RPAREN", "COMMA", "STRING_TYPE", "INT_TYPE", 
		"DECIMAL_TYPE", "BOOL_TYPE", "VOID_TYPE", "IDENTIFIER", "WS", "NEWLINE", 
		"COMMENT", "RAW_CONTENT", "RBRACKET"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlayscriptStructureLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlayscriptStructureLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,22,172,6,-1,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,
		6,7,6,2,7,7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,2,13,7,13,
		2,14,7,14,2,15,7,15,2,16,7,16,2,17,7,17,2,18,7,18,2,19,7,19,2,20,7,20,
		2,21,7,21,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,1,1,1,1,1,1,1,1,1,1,2,1,2,1,2,
		1,2,1,2,1,2,1,2,1,2,1,2,1,2,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,3,1,4,1,4,1,
		4,1,4,1,4,1,4,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,5,1,6,1,6,1,6,1,6,
		1,7,1,7,1,8,1,8,1,9,1,9,1,10,1,10,1,11,1,11,1,11,1,11,1,11,1,11,1,11,1,
		12,1,12,1,12,1,12,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,13,1,14,1,14,1,
		14,1,14,1,14,1,15,1,15,1,15,1,15,1,15,1,16,1,16,5,16,136,8,16,10,16,12,
		16,139,9,16,1,17,4,17,142,8,17,11,17,12,17,143,1,17,1,17,1,18,3,18,149,
		8,18,1,18,1,18,1,18,1,18,1,19,1,19,5,19,157,8,19,10,19,12,19,160,9,19,
		1,19,1,19,1,20,4,20,165,8,20,11,20,12,20,166,1,21,1,21,1,21,1,21,0,0,22,
		2,1,4,2,6,3,8,4,10,5,12,6,14,7,16,8,18,9,20,10,22,11,24,12,26,13,28,14,
		30,15,32,16,34,17,36,18,38,19,40,20,42,21,44,22,2,0,1,5,3,0,65,90,95,95,
		97,122,4,0,48,57,65,90,95,95,97,122,2,0,9,9,32,32,2,0,10,10,13,13,1,0,
		93,93,175,0,2,1,0,0,0,0,4,1,0,0,0,0,6,1,0,0,0,0,8,1,0,0,0,0,10,1,0,0,0,
		0,12,1,0,0,0,0,14,1,0,0,0,0,16,1,0,0,0,0,18,1,0,0,0,0,20,1,0,0,0,0,22,
		1,0,0,0,0,24,1,0,0,0,0,26,1,0,0,0,0,28,1,0,0,0,0,30,1,0,0,0,0,32,1,0,0,
		0,0,34,1,0,0,0,0,36,1,0,0,0,0,38,1,0,0,0,0,40,1,0,0,0,1,42,1,0,0,0,1,44,
		1,0,0,0,2,46,1,0,0,0,4,53,1,0,0,0,6,58,1,0,0,0,8,68,1,0,0,0,10,76,1,0,
		0,0,12,82,1,0,0,0,14,92,1,0,0,0,16,96,1,0,0,0,18,98,1,0,0,0,20,100,1,0,
		0,0,22,102,1,0,0,0,24,104,1,0,0,0,26,111,1,0,0,0,28,115,1,0,0,0,30,123,
		1,0,0,0,32,128,1,0,0,0,34,133,1,0,0,0,36,141,1,0,0,0,38,148,1,0,0,0,40,
		154,1,0,0,0,42,164,1,0,0,0,44,168,1,0,0,0,46,47,5,115,0,0,47,48,5,99,0,
		0,48,49,5,114,0,0,49,50,5,105,0,0,50,51,5,112,0,0,51,52,5,116,0,0,52,3,
		1,0,0,0,53,54,5,116,0,0,54,55,5,101,0,0,55,56,5,120,0,0,56,57,5,116,0,
		0,57,5,1,0,0,0,58,59,5,118,0,0,59,60,5,97,0,0,60,61,5,114,0,0,61,62,5,
		105,0,0,62,63,5,97,0,0,63,64,5,116,0,0,64,65,5,105,0,0,65,66,5,111,0,0,
		66,67,5,110,0,0,67,7,1,0,0,0,68,69,5,100,0,0,69,70,5,101,0,0,70,71,5,102,
		0,0,71,72,5,97,0,0,72,73,5,117,0,0,73,74,5,108,0,0,74,75,5,116,0,0,75,
		9,1,0,0,0,76,77,5,97,0,0,77,78,5,115,0,0,78,79,5,121,0,0,79,80,5,110,0,
		0,80,81,5,99,0,0,81,11,1,0,0,0,82,83,5,105,0,0,83,84,5,110,0,0,84,85,5,
		116,0,0,85,86,5,101,0,0,86,87,5,114,0,0,87,88,5,102,0,0,88,89,5,97,0,0,
		89,90,5,99,0,0,90,91,5,101,0,0,91,13,1,0,0,0,92,93,5,91,0,0,93,94,1,0,
		0,0,94,95,6,6,0,0,95,15,1,0,0,0,96,97,5,58,0,0,97,17,1,0,0,0,98,99,5,40,
		0,0,99,19,1,0,0,0,100,101,5,41,0,0,101,21,1,0,0,0,102,103,5,44,0,0,103,
		23,1,0,0,0,104,105,5,115,0,0,105,106,5,116,0,0,106,107,5,114,0,0,107,108,
		5,105,0,0,108,109,5,110,0,0,109,110,5,103,0,0,110,25,1,0,0,0,111,112,5,
		105,0,0,112,113,5,110,0,0,113,114,5,116,0,0,114,27,1,0,0,0,115,116,5,100,
		0,0,116,117,5,101,0,0,117,118,5,99,0,0,118,119,5,105,0,0,119,120,5,109,
		0,0,120,121,5,97,0,0,121,122,5,108,0,0,122,29,1,0,0,0,123,124,5,98,0,0,
		124,125,5,111,0,0,125,126,5,111,0,0,126,127,5,108,0,0,127,31,1,0,0,0,128,
		129,5,118,0,0,129,130,5,111,0,0,130,131,5,105,0,0,131,132,5,100,0,0,132,
		33,1,0,0,0,133,137,7,0,0,0,134,136,7,1,0,0,135,134,1,0,0,0,136,139,1,0,
		0,0,137,135,1,0,0,0,137,138,1,0,0,0,138,35,1,0,0,0,139,137,1,0,0,0,140,
		142,7,2,0,0,141,140,1,0,0,0,142,143,1,0,0,0,143,141,1,0,0,0,143,144,1,
		0,0,0,144,145,1,0,0,0,145,146,6,17,1,0,146,37,1,0,0,0,147,149,5,13,0,0,
		148,147,1,0,0,0,148,149,1,0,0,0,149,150,1,0,0,0,150,151,5,10,0,0,151,152,
		1,0,0,0,152,153,6,18,1,0,153,39,1,0,0,0,154,158,5,35,0,0,155,157,8,3,0,
		0,156,155,1,0,0,0,157,160,1,0,0,0,158,156,1,0,0,0,158,159,1,0,0,0,159,
		161,1,0,0,0,160,158,1,0,0,0,161,162,6,19,1,0,162,41,1,0,0,0,163,165,8,
		4,0,0,164,163,1,0,0,0,165,166,1,0,0,0,166,164,1,0,0,0,166,167,1,0,0,0,
		167,43,1,0,0,0,168,169,5,93,0,0,169,170,1,0,0,0,170,171,6,21,2,0,171,45,
		1,0,0,0,7,0,1,137,143,148,158,166,3,5,1,0,6,0,0,4,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
