//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyPlayscript/EasyPlayscript.Core/core/playscript/definition/PlayscriptStructureLexer.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.Parsing; 
using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public partial class PlayscriptStructureLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		LBRACKET=1, IDENTIFIER=2, WS=3, NEWLINE=4, COMMENT=5, RAW_CONTENT=6, RBRACKET=7;
	public const int
		IN_RAW=1;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE", "IN_RAW"
	};

	public static readonly string[] ruleNames = {
		"LBRACKET", "IDENTIFIER", "WS", "NEWLINE", "COMMENT", "RAW_CONTENT", "RBRACKET"
	};


	public PlayscriptStructureLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public PlayscriptStructureLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
		null, "'['", null, null, null, null, null, "']'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LBRACKET", "IDENTIFIER", "WS", "NEWLINE", "COMMENT", "RAW_CONTENT", 
		"RBRACKET"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "PlayscriptStructureLexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static PlayscriptStructureLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,7,59,6,-1,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,
		7,6,1,0,1,0,1,0,1,0,1,1,1,1,5,1,23,8,1,10,1,12,1,26,9,1,1,2,4,2,29,8,2,
		11,2,12,2,30,1,2,1,2,1,3,3,3,36,8,3,1,3,1,3,1,3,1,3,1,4,1,4,5,4,44,8,4,
		10,4,12,4,47,9,4,1,4,1,4,1,5,4,5,52,8,5,11,5,12,5,53,1,6,1,6,1,6,1,6,0,
		0,7,2,1,4,2,6,3,8,4,10,5,12,6,14,7,2,0,1,5,3,0,65,90,95,95,97,122,4,0,
		48,57,65,90,95,95,97,122,2,0,9,9,32,32,2,0,10,10,13,13,1,0,93,93,62,0,
		2,1,0,0,0,0,4,1,0,0,0,0,6,1,0,0,0,0,8,1,0,0,0,0,10,1,0,0,0,1,12,1,0,0,
		0,1,14,1,0,0,0,2,16,1,0,0,0,4,20,1,0,0,0,6,28,1,0,0,0,8,35,1,0,0,0,10,
		41,1,0,0,0,12,51,1,0,0,0,14,55,1,0,0,0,16,17,5,91,0,0,17,18,1,0,0,0,18,
		19,6,0,0,0,19,3,1,0,0,0,20,24,7,0,0,0,21,23,7,1,0,0,22,21,1,0,0,0,23,26,
		1,0,0,0,24,22,1,0,0,0,24,25,1,0,0,0,25,5,1,0,0,0,26,24,1,0,0,0,27,29,7,
		2,0,0,28,27,1,0,0,0,29,30,1,0,0,0,30,28,1,0,0,0,30,31,1,0,0,0,31,32,1,
		0,0,0,32,33,6,2,1,0,33,7,1,0,0,0,34,36,5,13,0,0,35,34,1,0,0,0,35,36,1,
		0,0,0,36,37,1,0,0,0,37,38,5,10,0,0,38,39,1,0,0,0,39,40,6,3,1,0,40,9,1,
		0,0,0,41,45,5,35,0,0,42,44,8,3,0,0,43,42,1,0,0,0,44,47,1,0,0,0,45,43,1,
		0,0,0,45,46,1,0,0,0,46,48,1,0,0,0,47,45,1,0,0,0,48,49,6,4,1,0,49,11,1,
		0,0,0,50,52,8,4,0,0,51,50,1,0,0,0,52,53,1,0,0,0,53,51,1,0,0,0,53,54,1,
		0,0,0,54,13,1,0,0,0,55,56,5,93,0,0,56,57,1,0,0,0,57,58,6,6,2,0,58,15,1,
		0,0,0,7,0,1,24,30,35,45,53,3,5,1,0,6,0,0,4,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
