using System.CodeDom.Compiler;
using System.IO;
using System.Text;
using EasyPlayscript.core.playscript.definition;

namespace EasyPlayscript.core.playscript;

public class PlayscriptCodeBuilder : PlayscriptParserBaseVisitor<string>
{
    private readonly string _fileName;
    private int _blockCounter;

    public PlayscriptCodeBuilder(string fileName)
    {
        _fileName = fileName;
    }

    public override string VisitPlayscript(PlayscriptParser.PlayscriptContext context)
    {
        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine("// <auto-generated/>");
        indented.WriteLine();
        indented.WriteLine("using EasyPlayscript.Generated;");
        indented.WriteLine();
        indented.WriteLine($"public static class {_fileName}");
        indented.WriteLine("{");
        indented.Indent++;
        indented.WriteLine("public static void Run(ScriptRegistry registry)");
        indented.WriteLine("{");
        indented.Indent++;

        foreach (var statement in context.statement())
        {
            var code = Visit(statement);
            if (!string.IsNullOrEmpty(code))
            {
                indented.Write(code);
            }
        }

        indented.Indent--;
        indented.WriteLine("}");
        indented.Indent--;
        indented.WriteLine("}");

        indented.Flush();
        return writer.ToString();
    }

    public override string VisitStatement(PlayscriptParser.StatementContext context)
    {
        if (context.scriptBlock() != null)
            return Visit(context.scriptBlock());
        if (context.externalCall() != null)
            return Visit(context.externalCall());
        return string.Empty;
    }

    public override string VisitScriptBlock(PlayscriptParser.ScriptBlockContext context)
    {
        var externalCall = context.externalCall();
        var identifier = externalCall.IDENTIFIER().GetText();
        var arg = externalCall.STRING_LITERAL().GetText();
        var cleanArg = arg.Trim('"');

        var blockVar = $"block{_blockCounter++}";

        using var writer = new StringWriter();
        var indented = new IndentedTextWriter(writer);

        indented.WriteLine($"var {blockVar} = new ScriptBlock();");

        foreach (var content in context.scriptContent())
        {
            var contentCode = Visit(content);
            if (!string.IsNullOrEmpty(contentCode))
            {
                indented.Write(contentCode);
            }
        }

        string handlerResult;
        switch (identifier)
        {
            case "script":
                handlerResult = PlayscriptHandlers.Script(cleanArg, context);
                break;
            case "text":
                handlerResult = PlayscriptHandlers.Text(cleanArg, context);
                break;
            default:
                handlerResult = $"// TODO: @{identifier}(\"{cleanArg}\")";
                break;
        }

        indented.WriteLine(handlerResult);

        indented.Flush();
        return writer.ToString();
    }

    public override string VisitScriptContent(PlayscriptParser.ScriptContentContext context)
    {
        if (context.sentence() != null)
            return Visit(context.sentence());
        if (context.internalCall() != null)
            return Visit(context.internalCall());
        return string.Empty;
    }

    public override string VisitSentence(PlayscriptParser.SentenceContext context)
    {
        var parts = context.sentencePart();
        var sb = new StringBuilder();
        foreach (var part in parts)
        {
            foreach (var text in part.TEXT())
            {
                sb.Append(text.GetText());
            }
        }
        return $"// TODO: sentence \"{sb}\"\n";
    }

    public override string VisitInternalCall(PlayscriptParser.InternalCallContext context)
    {
        var identifier = context.IDENTIFIER().GetText();
        var arg = context.STRING_LITERAL().GetText();
        return $"// TODO: @{identifier}({arg})\n";
    }

    public override string VisitExternalCall(PlayscriptParser.ExternalCallContext context)
    {
        var identifier = context.IDENTIFIER().GetText();
        var arg = context.STRING_LITERAL().GetText();
        return $"// TODO: top-level external call @{identifier}({arg})\n";
    }
}
