//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from EasyPlayscript/EasyPlayscript/core/playscript/definition/PlayscriptParser.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

 namespace EasyPlayscript.core.playscript.definition; 
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="PlayscriptParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IPlayscriptParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptParser.playscript"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlayscript([NotNull] PlayscriptParser.PlayscriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] PlayscriptParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptParser.externalCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternalCall([NotNull] PlayscriptParser.ExternalCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptParser.scriptBlock"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScriptBlock([NotNull] PlayscriptParser.ScriptBlockContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptParser.scriptContent"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScriptContent([NotNull] PlayscriptParser.ScriptContentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptParser.sentence"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentence([NotNull] PlayscriptParser.SentenceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptParser.sentencePart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSentencePart([NotNull] PlayscriptParser.SentencePartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="PlayscriptParser.internalCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInternalCall([NotNull] PlayscriptParser.InternalCallContext context);
}
